import type { ActorHub, ActorHubLink } from "@/lib/actors/types";

export const actorHubMockItems = [
  {
    id: "actor-csn",
    title: "Companhia Siderúrgica Nacional",
    slug: "companhia-siderurgica-nacional",
    excerpt: "Empresa-símbolo da siderurgia e da disputa ambiental da cidade.",
    description:
      "A CSN atravessa o arquivo do VR Abandonada como ator recorrente de conflito, memória e consequência pública. Ela ajuda a ler o cruzamento entre indústria, bairro, saúde e meio ambiente.",
    lead_question: "Como uma empresa molda ar, bairro e rotina sem desaparecer do debate público?",
    actor_type: "empresa",
    territory_label: "Cidade e entorno industrial",
    cover_image_url: "/editorial/covers/arquivo-inicial.svg",
    featured: true,
    public_visibility: true,
    status: "active",
    sort_order: 1,
    created_at: "2026-01-08T12:00:00.000Z",
    updated_at: "2026-01-08T12:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "actor-prefeitura-vr",
    title: "Prefeitura Municipal de Volta Redonda",
    slug: "prefeitura-municipal-de-volta-redonda",
    excerpt: "Poder executivo local que atravessa obras, filas, manutenção e abandono urbano.",
    description:
      "A prefeitura aparece como agente de decisão e também como campo de resposta pública. O projeto a lê como responsável por parte importante da forma urbana e da prestação de serviços.",
    lead_question: "O que muda quando a cidade espera resposta do poder local?",
    actor_type: "orgao_publico",
    territory_label: "Centro administrativo",
    cover_image_url: "/archive/assets/acervo-mapa.svg",
    featured: true,
    public_visibility: true,
    status: "monitoring",
    sort_order: 2,
    created_at: "2026-01-08T12:10:00.000Z",
    updated_at: "2026-01-08T12:10:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "actor-hsjb",
    title: "Hospital São João Batista",
    slug: "hospital-sao-joao-batista",
    excerpt: "Equipamento público onde saúde, fila e desgaste ganham forma concreta.",
    description:
      "O hospital organiza uma parte importante da leitura sobre cuidado, urgência e consequência do trabalho e do ambiente na vida urbana. Ele entra como lugar de responsabilidade pública e de pressão cotidiana.",
    lead_question: "O que a cidade joga para dentro da fila do hospital?",
    actor_type: "hospital",
    territory_label: "Cidade do cuidado",
    cover_image_url: "/archive/assets/acervo-relatorio.svg",
    featured: false,
    public_visibility: true,
    status: "active",
    sort_order: 3,
    created_at: "2026-01-08T12:20:00.000Z",
    updated_at: "2026-01-08T12:20:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "actor-saude-vr",
    title: "Secretaria Municipal de Saúde",
    slug: "secretaria-municipal-de-saude",
    excerpt: "Área administrativa que mostra como a rede de cuidado responde ou falha em público.",
    description:
      "A secretaria entra como peça estrutural para ler orçamento, prioridade, fila e cobertura de saúde. O ator ajuda a entender o que é decisão política e o que vira desgaste da população.",
    lead_question: "Quem responde quando a saúde vira espera?",
    actor_type: "secretaria",
    territory_label: "Rede municipal de saúde",
    cover_image_url: "/archive/assets/acervo-foto-oficina.svg",
    featured: false,
    public_visibility: true,
    status: "monitoring",
    sort_order: 4,
    created_at: "2026-01-08T12:30:00.000Z",
    updated_at: "2026-01-08T12:30:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "actor-ifrj-vr",
    title: "IFRJ - Campus Volta Redonda",
    slug: "ifrj-campus-volta-redonda",
    excerpt: "Instituição educacional ligada à formação, memória técnica e cidade operária.",
    description:
      "A presença educacional ajuda a entender como conhecimento, formação e território se cruzam na cidade. O projeto o trata como espaço de memória do trabalho e de futuro público.",
    lead_question: "Como a formação também escreve a cidade?",
    actor_type: "universidade",
    territory_label: "Cidade operária e formação",
    cover_image_url: "/editorial/covers/arquivo-inicial.svg",
    featured: false,
    public_visibility: true,
    status: "archive",
    sort_order: 5,
    created_at: "2026-01-08T12:40:00.000Z",
    updated_at: "2026-01-08T12:40:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "actor-saae-vr",
    title: "SAAE - Serviço Autônomo de Água e Esgoto",
    slug: "saae-servico-autonomo-de-agua-e-esgoto",
    excerpt: "Autarquia que organiza parte da disputa sobre saneamento, manutenção e resposta urbana.",
    description:
      "O SAAE aparece como ator recorrente quando o problema atravessa água, saneamento e reparo urbano. Ele ajuda a conectar infraestrutura e consequência pública.",
    lead_question: "Quem sustenta a água da cidade quando o sistema falha?",
    actor_type: "autarquia",
    territory_label: "Rede urbana e saneamento",
    cover_image_url: "/archive/assets/acervo-recorte-jornal.svg",
    featured: false,
    public_visibility: true,
    status: "monitoring",
    sort_order: 6,
    created_at: "2026-01-08T12:50:00.000Z",
    updated_at: "2026-01-08T12:50:00.000Z",
    created_by: null,
    updated_by: null,
  },
] satisfies ActorHub[];

export const actorHubLinkMockItems = [
  {
    id: "actor-link-csn-1",
    actor_hub_id: "actor-csn",
    link_type: "editorial",
    link_key: "ar-poeira-e-pressao",
    link_role: "lead",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Pauta de entrada sobre ar e pressão industrial.",
    featured: true,
    sort_order: 1,
    created_at: "2026-01-08T13:00:00.000Z",
    updated_at: "2026-01-08T13:00:00.000Z",
  },
  {
    id: "actor-link-csn-2",
    actor_hub_id: "actor-csn",
    link_type: "dossier",
    link_key: "ar-fumaca-e-rotina-industrial",
    link_role: "context",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Dossiê que organiza a investigação de base.",
    featured: true,
    sort_order: 2,
    created_at: "2026-01-08T13:02:00.000Z",
    updated_at: "2026-01-08T13:02:00.000Z",
  },
  {
    id: "actor-link-csn-3",
    actor_hub_id: "actor-csn",
    link_type: "memory",
    link_key: "poeira-e-fumaca",
    link_role: "archive",
    timeline_year: 1997,
    timeline_label: "fim dos anos 1990",
    timeline_note: "Memória territorial da fumaça recorrente.",
    featured: false,
    sort_order: 3,
    created_at: "2026-01-08T13:04:00.000Z",
    updated_at: "2026-01-08T13:04:00.000Z",
  },
  {
    id: "actor-link-csn-4",
    actor_hub_id: "actor-csn",
    link_type: "campaign",
    link_key: "respira-volta-redonda",
    link_role: "followup",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Chamado público que mantém a frente ativa.",
    featured: false,
    sort_order: 4,
    created_at: "2026-01-08T13:06:00.000Z",
    updated_at: "2026-01-08T13:06:00.000Z",
  },
  {
    id: "actor-link-csn-5",
    actor_hub_id: "actor-csn",
    link_type: "impact",
    link_key: "respira-volta-redonda",
    link_role: "followup",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Efeito público observado da mobilização.",
    featured: false,
    sort_order: 5,
    created_at: "2026-01-08T13:08:00.000Z",
    updated_at: "2026-01-08T13:08:00.000Z",
  },
  {
    id: "actor-link-csn-6",
    actor_hub_id: "actor-csn",
    link_type: "territory",
    link_key: "csn-e-entorno",
    link_role: "context",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Território de pressão e leitura do entorno industrial.",
    featured: true,
    sort_order: 6,
    created_at: "2026-01-08T13:10:00.000Z",
    updated_at: "2026-01-08T13:10:00.000Z",
  },
  {
    id: "actor-link-csn-7",
    actor_hub_id: "actor-csn",
    link_type: "territory",
    link_key: "cidade-operaria",
    link_role: "archive",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Bairro que organiza a memória operária da cidade.",
    featured: false,
    sort_order: 7,
    created_at: "2026-01-08T13:12:00.000Z",
    updated_at: "2026-01-08T13:12:00.000Z",
  },
  {
    id: "actor-link-prefeitura-1",
    actor_hub_id: "actor-prefeitura-vr",
    link_type: "editorial",
    link_key: "o-que-sobrou-da-promessa-industrial",
    link_role: "lead",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Pauta de entrada sobre promessa e ruína urbana.",
    featured: true,
    sort_order: 1,
    created_at: "2026-01-08T13:14:00.000Z",
    updated_at: "2026-01-08T13:14:00.000Z",
  },
  {
    id: "actor-link-prefeitura-2",
    actor_hub_id: "actor-prefeitura-vr",
    link_type: "dossier",
    link_key: "cidade-e-abandono",
    link_role: "context",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Dossiê que amarra o abandono urbano ao poder local.",
    featured: true,
    sort_order: 2,
    created_at: "2026-01-08T13:16:00.000Z",
    updated_at: "2026-01-08T13:16:00.000Z",
  },
  {
    id: "actor-link-prefeitura-3",
    actor_hub_id: "actor-prefeitura-vr",
    link_type: "memory",
    link_key: "apagamentos-do-centro",
    link_role: "archive",
    timeline_year: 1985,
    timeline_label: "requalificações urbanas",
    timeline_note: "Memória que ajuda a ler apagamentos no centro.",
    featured: false,
    sort_order: 3,
    created_at: "2026-01-08T13:18:00.000Z",
    updated_at: "2026-01-08T13:18:00.000Z",
  },
  {
    id: "actor-link-prefeitura-4",
    actor_hub_id: "actor-prefeitura-vr",
    link_type: "impact",
    link_key: "arquivo-que-volta-a-falar",
    link_role: "followup",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Consequência pública ligada à memória reativada.",
    featured: false,
    sort_order: 4,
    created_at: "2026-01-08T13:20:00.000Z",
    updated_at: "2026-01-08T13:20:00.000Z",
  },
  {
    id: "actor-link-prefeitura-5",
    actor_hub_id: "actor-prefeitura-vr",
    link_type: "territory",
    link_key: "praca-savio-gama",
    link_role: "context",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Marco urbano do centro e da disputa por forma pública.",
    featured: true,
    sort_order: 5,
    created_at: "2026-01-08T13:22:00.000Z",
    updated_at: "2026-01-08T13:22:00.000Z",
  },
  {
    id: "actor-link-prefeitura-6",
    actor_hub_id: "actor-prefeitura-vr",
    link_type: "territory",
    link_key: "rodoviaria-nova",
    link_role: "followup",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Ponto crítico que mostra a espera e a fricção urbana.",
    featured: false,
    sort_order: 6,
    created_at: "2026-01-08T13:24:00.000Z",
    updated_at: "2026-01-08T13:24:00.000Z",
  },
  {
    id: "actor-link-hsjb-1",
    actor_hub_id: "actor-hsjb",
    link_type: "editorial",
    link_key: "turno-risco-e-lesao",
    link_role: "lead",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Pauta sobre risco, lesão e trabalho.",
    featured: true,
    sort_order: 1,
    created_at: "2026-01-08T13:26:00.000Z",
    updated_at: "2026-01-08T13:26:00.000Z",
  },
  {
    id: "actor-link-hsjb-2",
    actor_hub_id: "actor-hsjb",
    link_type: "dossier",
    link_key: "trabalho-ferido-corpo-insistente",
    link_role: "context",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Dossiê que organiza a investigação de trabalho.",
    featured: true,
    sort_order: 2,
    created_at: "2026-01-08T13:28:00.000Z",
    updated_at: "2026-01-08T13:28:00.000Z",
  },
  {
    id: "actor-link-hsjb-3",
    actor_hub_id: "actor-hsjb",
    link_type: "memory",
    link_key: "acidente-e-turno",
    link_role: "archive",
    timeline_year: 2004,
    timeline_label: "2004",
    timeline_note: "Memória do corpo em turno e acidente.",
    featured: false,
    sort_order: 3,
    created_at: "2026-01-08T13:30:00.000Z",
    updated_at: "2026-01-08T13:30:00.000Z",
  },
  {
    id: "actor-link-hsjb-4",
    actor_hub_id: "actor-hsjb",
    link_type: "campaign",
    link_key: "trabalho-sob-observacao",
    link_role: "followup",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Chamado que mantém o caso em circulação.",
    featured: false,
    sort_order: 4,
    created_at: "2026-01-08T13:32:00.000Z",
    updated_at: "2026-01-08T13:32:00.000Z",
  },
  {
    id: "actor-link-hsjb-5",
    actor_hub_id: "actor-hsjb",
    link_type: "impact",
    link_key: "trabalho-sob-observacao",
    link_role: "followup",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Impacto de monitoramento do caso.",
    featured: false,
    sort_order: 5,
    created_at: "2026-01-08T13:34:00.000Z",
    updated_at: "2026-01-08T13:34:00.000Z",
  },
  {
    id: "actor-link-hsjb-6",
    actor_hub_id: "actor-hsjb",
    link_type: "territory",
    link_key: "hospital-sao-joao-batista",
    link_role: "context",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Lugar físico onde o conflito aparece na cidade.",
    featured: true,
    sort_order: 6,
    created_at: "2026-01-08T13:36:00.000Z",
    updated_at: "2026-01-08T13:36:00.000Z",
  },
  {
    id: "actor-link-saude-1",
    actor_hub_id: "actor-saude-vr",
    link_type: "editorial",
    link_key: "linha-tarifa-e-espera",
    link_role: "lead",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Pauta sobre rede e espera na cidade.",
    featured: true,
    sort_order: 1,
    created_at: "2026-01-08T13:38:00.000Z",
    updated_at: "2026-01-08T13:38:00.000Z",
  },
  {
    id: "actor-link-saude-2",
    actor_hub_id: "actor-saude-vr",
    link_type: "dossier",
    link_key: "cidade-e-abandono",
    link_role: "context",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Dossiê sobre manutenção e abandono urbano.",
    featured: true,
    sort_order: 2,
    created_at: "2026-01-08T13:40:00.000Z",
    updated_at: "2026-01-08T13:40:00.000Z",
  },
  {
    id: "actor-link-saude-3",
    actor_hub_id: "actor-saude-vr",
    link_type: "territory",
    link_key: "vila-santa-cecilia",
    link_role: "context",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Território onde o cuidado público aparece na rotina.",
    featured: false,
    sort_order: 3,
    created_at: "2026-01-08T13:42:00.000Z",
    updated_at: "2026-01-08T13:42:00.000Z",
  },
  {
    id: "actor-link-saude-4",
    actor_hub_id: "actor-saude-vr",
    link_type: "impact",
    link_key: "arquivo-que-volta-a-falar",
    link_role: "followup",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Efeito público ligado ao arquivo reativado.",
    featured: false,
    sort_order: 4,
    created_at: "2026-01-08T13:44:00.000Z",
    updated_at: "2026-01-08T13:44:00.000Z",
  },
  {
    id: "actor-link-saude-5",
    actor_hub_id: "actor-saude-vr",
    link_type: "actor",
    link_key: "hospital-sao-joao-batista",
    link_role: "context",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Actor complementar na rede de saúde.",
    featured: false,
    sort_order: 5,
    created_at: "2026-01-08T13:46:00.000Z",
    updated_at: "2026-01-08T13:46:00.000Z",
  },
  {
    id: "actor-link-ifrj-1",
    actor_hub_id: "actor-ifrj-vr",
    link_type: "memory",
    link_key: "greve-e-fabrica",
    link_role: "lead",
    timeline_year: 1950,
    timeline_label: "década de 1950",
    timeline_note: "Memória de formação operária e técnica.",
    featured: true,
    sort_order: 1,
    created_at: "2026-01-08T13:48:00.000Z",
    updated_at: "2026-01-08T13:48:00.000Z",
  },
  {
    id: "actor-link-ifrj-2",
    actor_hub_id: "actor-ifrj-vr",
    link_type: "editorial",
    link_key: "o-que-sobrou-da-promessa-industrial",
    link_role: "context",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Pauta que atravessa a memória do bairro operário.",
    featured: false,
    sort_order: 2,
    created_at: "2026-01-08T13:50:00.000Z",
    updated_at: "2026-01-08T13:50:00.000Z",
  },
  {
    id: "actor-link-ifrj-3",
    actor_hub_id: "actor-ifrj-vr",
    link_type: "territory",
    link_key: "vila-santa-cecilia",
    link_role: "context",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "O lugar onde formação e bairro se cruzam.",
    featured: false,
    sort_order: 3,
    created_at: "2026-01-08T13:52:00.000Z",
    updated_at: "2026-01-08T13:52:00.000Z",
  },
  {
    id: "actor-link-ifrj-4",
    actor_hub_id: "actor-ifrj-vr",
    link_type: "hub",
    link_key: "memoria-de-volta-redonda",
    link_role: "archive",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Eixo de memória maior que enquadra o recorte.",
    featured: false,
    sort_order: 4,
    created_at: "2026-01-08T13:54:00.000Z",
    updated_at: "2026-01-08T13:54:00.000Z",
  },
  {
    id: "actor-link-saae-1",
    actor_hub_id: "actor-saae-vr",
    link_type: "editorial",
    link_key: "linha-tarifa-e-espera",
    link_role: "lead",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Pauta sobre rede e espera urbana.",
    featured: true,
    sort_order: 1,
    created_at: "2026-01-08T13:56:00.000Z",
    updated_at: "2026-01-08T13:56:00.000Z",
  },
  {
    id: "actor-link-saae-2",
    actor_hub_id: "actor-saae-vr",
    link_type: "dossier",
    link_key: "cidade-e-abandono",
    link_role: "context",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Dossiê sobre manutenção e abandono urbano.",
    featured: false,
    sort_order: 2,
    created_at: "2026-01-08T13:58:00.000Z",
    updated_at: "2026-01-08T13:58:00.000Z",
  },
  {
    id: "actor-link-saae-3",
    actor_hub_id: "actor-saae-vr",
    link_type: "territory",
    link_key: "rodoviaria-nova",
    link_role: "followup",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Ponto crítico ligado à circulação e ao saneamento urbano.",
    featured: true,
    sort_order: 3,
    created_at: "2026-01-08T14:00:00.000Z",
    updated_at: "2026-01-08T14:00:00.000Z",
  },
  {
    id: "actor-link-saae-4",
    actor_hub_id: "actor-saae-vr",
    link_type: "impact",
    link_key: "arquivo-que-volta-a-falar",
    link_role: "followup",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Efeito público ligado à documentação do saneamento.",
    featured: false,
    sort_order: 4,
    created_at: "2026-01-08T14:02:00.000Z",
    updated_at: "2026-01-08T14:02:00.000Z",
  },
] satisfies ActorHubLink[];
