import type { EntryRoute, EntryRouteItem } from "@/lib/entry-routes/types";

export const entryRouteMockItems: EntryRoute[] = [
  {
    id: "entry-route-1",
    title: "Entenda o projeto em 5 minutos",
    slug: "entenda-o-projeto-em-5-minutos",
    excerpt: "Um caminho curto para quem chega agora e quer entender o que é o VR Abandonada.",
    description:
      "Rota de entrada para visitantes novos. Começa pelo manifesto, atravessa pauta, memória e arquivo, e termina em um convite claro para seguir acompanhando o projeto.",
    audience_label: "Primeira visita",
    featured: true,
    public_visibility: true,
    sort_order: 1,
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    created_by: null,
    updated_by: null,
  },
  {
    id: "entry-route-2",
    title: "Comece pela poluição e CSN",
    slug: "comece-pela-poluicao-e-csn",
    excerpt: "A porta de entrada para quem quer ler a cidade a partir do conflito ambiental e industrial.",
    description:
      "Uma rota temática que começa no eixo, passa pelo dossiê, mostra evidências documentais e termina em memória e pauta.",
    audience_label: "Quem quer tema",
    featured: true,
    public_visibility: true,
    sort_order: 2,
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    created_by: null,
    updated_by: null,
  },
  {
    id: "entry-route-3",
    title: "Comece pela memória da cidade",
    slug: "comece-pela-memoria-da-cidade",
    excerpt: "Para quem quer entender o arquivo vivo antes de entrar nas pautas.",
    description:
      "Percurso que parte da memória, sobe para o acervo e volta para os casos e eixos que ajudam a ler o presente.",
    audience_label: "Arquivo e história",
    featured: true,
    public_visibility: true,
    sort_order: 3,
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    created_by: null,
    updated_by: null,
  },
  {
    id: "entry-route-4",
    title: "Acompanhe o que está em curso agora",
    slug: "acompanhe-o-que-esta-em-curso-agora",
    excerpt: "Para quem quer entender o ritmo presente do projeto sem se perder.",
    description:
      "Rota voltada ao radar editorial e aos dossiês em andamento. Mostra o que mudou, o que está quente e o que convoca retorno.",
    audience_label: "Retorno recorrente",
    featured: true,
    public_visibility: true,
    sort_order: 4,
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    created_by: null,
    updated_by: null,
  },
];

export const entryRouteItemMockItems: EntryRouteItem[] = [
  { id: "entry-route-item-1", route_id: "entry-route-1", item_type: "editorial", item_key: "o-que-sobrou-da-promessa-industrial", role: "start", sort_order: 1, note: "Abrir com uma pauta forte e atual.", created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: "entry-route-item-2", route_id: "entry-route-1", item_type: "dossier", item_key: "ar-fumaca-e-rotina-industrial", role: "context", sort_order: 2, note: "Amarra o caso em curso.", created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: "entry-route-item-3", route_id: "entry-route-1", item_type: "memory", item_key: "cidade-operaria", role: "proof", sort_order: 3, note: "Memória-base da cidade operária.", created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: "entry-route-item-4", route_id: "entry-route-1", item_type: "archive", item_key: "archive-mock-4", role: "deepen", sort_order: 4, note: "Recorte documental para aprofundar.", created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: "entry-route-item-5", route_id: "entry-route-2", item_type: "hub", item_key: "poluicao-e-csn", role: "start", sort_order: 1, note: "Comece pelo tema.", created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: "entry-route-item-6", route_id: "entry-route-2", item_type: "dossier", item_key: "ar-fumaca-e-rotina-industrial", role: "proof", sort_order: 2, note: "Dossiê que organiza a investigação.", created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: "entry-route-item-7", route_id: "entry-route-2", item_type: "archive", item_key: "archive-mock-1", role: "proof", sort_order: 3, note: "Material de base do conflito.", created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: "entry-route-item-8", route_id: "entry-route-2", item_type: "memory", item_key: "poluicao-e-industria", role: "context", sort_order: 4, note: "Memória histórica do eixo.", created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: "entry-route-item-9", route_id: "entry-route-3", item_type: "memory", item_key: "cidade-operaria", role: "start", sort_order: 1, note: "Entrada por arquivo vivo.", created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: "entry-route-item-10", route_id: "entry-route-3", item_type: "archive", item_key: "archive-mock-2", role: "proof", sort_order: 2, note: "Fonte visual do arquivo.", created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: "entry-route-item-11", route_id: "entry-route-3", item_type: "editorial", item_key: "linha-tarifa-e-espera", role: "follow", sort_order: 3, note: "Mostra como a memória atravessa a pauta atual.", created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: "entry-route-item-12", route_id: "entry-route-4", item_type: "dossier", item_key: "trabalho-ferido-corpo-insistente", role: "start", sort_order: 1, note: "Caso em andamento.", created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: "entry-route-item-13", route_id: "entry-route-4", item_type: "editorial", item_key: "turno-risco-e-lesao", role: "context", sort_order: 2, note: "Pauta que acompanha o caso.", created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: "entry-route-item-14", route_id: "entry-route-4", item_type: "hub", item_key: "trabalho-e-acidentes", role: "deepen", sort_order: 3, note: "Frente temática maior.", created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: "entry-route-item-15", route_id: "entry-route-4", item_type: "archive", item_key: "archive-mock-3", role: "proof", sort_order: 4, note: "Documento para ancorar a leitura.", created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
];
