import type { EditorialEntry } from "@/lib/entrada/types";

const now = new Date().toISOString();

export const editorialEntryMockItems: EditorialEntry[] = [
  {
    id: "entry-post-1",
    entry_type: "post",
    entry_status: "ready_for_enrichment",
    target_surface: "agora",
    title: "Fumaça voltou a pesar no entorno da CSN",
    summary: "Registro rápido para abrir o radar do dia e decidir o próximo passo.",
    details: "Anotação curta de campo sobre o ar pesado, a recorrência do incômodo e a necessidade de manter o caso em circulação pública.",
    file_url: null,
    file_path: null,
    file_name: null,
    source_label: "Registro rápido",
    year_label: null,
    approximate_year: null,
    place_label: "CSN e entorno",
    territory_label: "CSN e entorno",
    actor_label: "Companhia Siderúrgica Nacional",
    axis_label: "Poluição e CSN",
    notes: "Pode virar radar, pauta ou edição curta.",
    featured: true,
    sort_order: 0,
    published_at: now,
    created_at: now,
    updated_at: now,
    created_by: null,
    updated_by: null,
  },
  {
    id: "entry-document-1",
    entry_type: "document",
    entry_status: "stored",
    target_surface: "acervo",
    title: "Relatório sobre poeira e saúde",
    summary: "Documento técnico para guardar agora e enriquecer depois.",
    details: "Material de apoio sobre poeira, rotina industrial e impacto sobre a cidade.",
    file_url: null,
    file_path: null,
    file_name: null,
    source_label: "Relatório público",
    year_label: "2024",
    approximate_year: 2024,
    place_label: "Vila Santa Cecília",
    territory_label: "CSN e entorno",
    actor_label: "CSN",
    axis_label: "Poluição e CSN",
    notes: "Base para acervo e resumo editorial posterior.",
    featured: false,
    sort_order: 1,
    published_at: null,
    created_at: now,
    updated_at: now,
    created_by: null,
    updated_by: null,
  },
  {
    id: "entry-image-1",
    entry_type: "image",
    entry_status: "ready_for_enrichment",
    target_surface: "memoria",
    title: "Recorte de jornal sobre turno e acidente",
    summary: "Imagem histórica para guardar no acervo e depois ligar à memória.",
    details: "Recorte visual que ajuda a ler o risco, o turno e a normalização do acidente no trabalho.",
    file_url: null,
    file_path: null,
    file_name: null,
    source_label: "Arquivo de jornal",
    year_label: "aprox. 1998",
    approximate_year: 1998,
    place_label: "Cidade operária",
    territory_label: "Cidade operária",
    actor_label: "Hospital São João Batista",
    axis_label: "Trabalho e acidentes",
    notes: "Pode virar memória ou anexo de acervo.",
    featured: false,
    sort_order: 2,
    published_at: null,
    created_at: now,
    updated_at: now,
    created_by: null,
    updated_by: null,
  },
];
