import type { InvestigationDossier, InvestigationDossierLink, InvestigationDossierUpdate } from "@/lib/dossiers/types";

export const investigationDossierMockItems: InvestigationDossier[] = [
  {
    id: "dossier-1",
    title: "Ar, fumaça e rotina industrial",
    slug: "ar-fumaca-e-rotina-industrial",
    excerpt: "Um dossiê vivo sobre poluição, corpo e custo cotidiano em volta da siderurgia.",
    description:
      "Este dossiê reúne pauta, memória e acervo para investigar o que o entorno industrial produz no ar, no bairro e no modo de viver a cidade.",
    status: "in_progress",
    cover_image_url: "/archive/assets/acervo-recorte-jornal.svg",
    featured: true,
    public_visibility: true,
    sort_order: 1,
    lead_question: "Quem paga o custo ambiental da cidade e como isso se naturalizou?",
    period_label: "Anos 1990-2020",
    territory_label: "Aterrado e entorno industrial",
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "dossier-2",
    title: "Trabalho ferido, corpo insistente",
    slug: "trabalho-ferido-corpo-insistente",
    excerpt: "Investigação sobre acidente, desgaste e o que o trabalho deixa como marca pública.",
    description:
      "Dossiê sobre lesão, turno, pressão e a normalização do risco. Junta relato, documento e pauta para entender o problema como estrutura.",
    status: "monitoring",
    cover_image_url: "/archive/assets/acervo-relatorio.svg",
    featured: true,
    public_visibility: true,
    sort_order: 2,
    lead_question: "Quando o acidente deixa de ser exceção e vira rotina administrativa?",
    period_label: "Anos 2000-2020",
    territory_label: "Volta Grande e bairros operários",
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "dossier-3",
    title: "Cidade e abandono",
    slug: "cidade-e-abandono",
    excerpt: "Como o desgaste urbano vira rotina e reordena o acesso à cidade.",
    description:
      "Dossiê sobre transporte, saneamento, equipamentos públicos e o modo como a falta de manutenção atravessa o cotidiano.",
    status: "concluded",
    cover_image_url: "/archive/assets/acervo-foto-oficina.svg",
    featured: false,
    public_visibility: true,
    sort_order: 3,
    lead_question: "O que a cidade deixa cair quando o abandono vira política normal?",
    period_label: "Anos 2010-2026",
    territory_label: "Centro e bairros espraiados",
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
];

export const investigationDossierLinkMockItems: InvestigationDossierLink[] = [
  {
    id: "dossier-link-1",
    dossier_id: "dossier-1",
    link_type: "editorial",
    link_key: "ar-poeira-e-pressao",
    link_role: "lead",
    timeline_year: 2024,
    timeline_label: "2024",
    timeline_note: "Entrada principal da investigação sobre poeira, pressão e custo cotidiano.",
    featured: true,
    sort_order: 1,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
  },
  {
    id: "dossier-link-2",
    dossier_id: "dossier-1",
    link_type: "memory",
    link_key: "poeira-e-fumaca",
    link_role: "context",
    timeline_year: 1997,
    timeline_label: "fim dos anos 1990",
    timeline_note: "Memória territorial sobre a permanência da fumaça no bairro.",
    featured: true,
    sort_order: 2,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
  },
  {
    id: "dossier-link-3",
    dossier_id: "dossier-1",
    link_type: "archive",
    link_key: "archive-mock-2",
    link_role: "evidence",
    timeline_year: 2008,
    timeline_label: "2008",
    timeline_note: "Documento-base ligado a poeira industrial e pressão cotidiana.",
    featured: false,
    sort_order: 3,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
  },
  {
    id: "dossier-link-4",
    dossier_id: "dossier-1",
    link_type: "collection",
    link_key: "poluicao-e-industria",
    link_role: "archive",
    timeline_year: 2016,
    timeline_label: "2016",
    timeline_note: "Coleção que concentra o recorte documental da poluição.",
    featured: false,
    sort_order: 4,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
  },
  {
    id: "dossier-link-5",
    dossier_id: "dossier-1",
    link_type: "series",
    link_key: "poluicao-e-csn",
    link_role: "followup",
    timeline_year: 2025,
    timeline_label: "2025",
    timeline_note: "Linha em curso que mantém a pergunta aberta.",
    featured: false,
    sort_order: 5,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
  },
  {
    id: "dossier-link-6",
    dossier_id: "dossier-2",
    link_type: "editorial",
    link_key: "turno-risco-e-lesao",
    link_role: "lead",
    timeline_year: 2025,
    timeline_label: "2025",
    timeline_note: "Peça central sobre acidente, turno e desgaste corporal.",
    featured: true,
    sort_order: 1,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
  },
  {
    id: "dossier-link-7",
    dossier_id: "dossier-2",
    link_type: "memory",
    link_key: "acidente-e-turno",
    link_role: "context",
    timeline_year: 2004,
    timeline_label: "2004",
    timeline_note: "Memória sobre a normalização do risco no turno.",
    featured: true,
    sort_order: 2,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
  },
  {
    id: "dossier-link-8",
    dossier_id: "dossier-2",
    link_type: "archive",
    link_key: "archive-mock-3",
    link_role: "evidence",
    timeline_year: 2010,
    timeline_label: "2010",
    timeline_note: "Arquivo que sustenta a leitura sobre lesão e pressão.",
    featured: false,
    sort_order: 3,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
  },
  {
    id: "dossier-link-9",
    dossier_id: "dossier-2",
    link_type: "collection",
    link_key: "trabalho-e-acidentes",
    link_role: "archive",
    timeline_year: 2018,
    timeline_label: "2018",
    timeline_note: "Coleção de documentos e recortes sobre acidentes e trabalho.",
    featured: false,
    sort_order: 4,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
  },
  {
    id: "dossier-link-10",
    dossier_id: "dossier-2",
    link_type: "series",
    link_key: "trabalho-e-acidentes",
    link_role: "followup",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Desdobramento público do caso no tempo presente.",
    featured: false,
    sort_order: 5,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
  },
  {
    id: "dossier-link-11",
    dossier_id: "dossier-3",
    link_type: "editorial",
    link_key: "o-que-sobrou-da-promessa-industrial",
    link_role: "lead",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Entrada central do dossiê sobre abandono urbano.",
    featured: true,
    sort_order: 1,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
  },
  {
    id: "dossier-link-12",
    dossier_id: "dossier-3",
    link_type: "memory",
    link_key: "apagamentos-e-disputas",
    link_role: "context",
    timeline_year: 1990,
    timeline_label: "anos 1990",
    timeline_note: "Memória sobre apagamentos e disputa do território.",
    featured: true,
    sort_order: 2,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
  },
  {
    id: "dossier-link-13",
    dossier_id: "dossier-3",
    link_type: "archive",
    link_key: "archive-mock-1",
    link_role: "evidence",
    timeline_year: 2012,
    timeline_label: "2012",
    timeline_note: "Fonte documental sobre a cidade deixada em suspenso.",
    featured: false,
    sort_order: 3,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
  },
  {
    id: "dossier-link-14",
    dossier_id: "dossier-3",
    link_type: "collection",
    link_key: "cidade-operaria",
    link_role: "archive",
    timeline_year: 2019,
    timeline_label: "2019",
    timeline_note: "Coleção que concentra o recorte urbano-operário.",
    featured: false,
    sort_order: 4,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
  },
  {
    id: "dossier-link-15",
    dossier_id: "dossier-3",
    link_type: "series",
    link_key: "cidade-e-abandono",
    link_role: "followup",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Linha de continuidade do abandono urbano.",
    featured: false,
    sort_order: 5,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
  },
];

export const investigationDossierUpdateMockItems: InvestigationDossierUpdate[] = [
  {
    id: "dossier-update-1",
    dossier_id: "dossier-1",
    title: "Nova rodada de relatos reforça a pressão na borda industrial",
    slug: "nova-rodada-relatos-pressao-borda-industrial",
    excerpt: "Moradores voltaram a descrever poeira, odor e piora em horários de pico.",
    body:
      "A investigação recebeu novos relatos no entorno do recorte principal. O material reforça a leitura de que o problema não é episódico: ele reaparece em horários previsíveis, atravessa rotinas de trabalho e volta a reorganizar o cotidiano do bairro.",
    update_type: "development",
    published: true,
    published_at: "2026-03-18T18:30:00.000Z",
    featured: true,
    sort_order: 1,
    created_at: "2026-03-18T18:30:00.000Z",
    updated_at: "2026-03-18T18:30:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "dossier-update-2",
    dossier_id: "dossier-1",
    title: "Documento de apoio confirma a linha de tempo do recorte",
    slug: "documento-apoio-confirma-linha-tempo-recorte",
    excerpt: "Um anexo de arquivo ajuda a costurar a cronologia pública do caso.",
    body:
      "A checagem do documento-base confirmou a sequência temporal que já aparecia em relatos e memórias territoriais. O dossiê segue em aberto para receber novas pistas e localizar o lastro material do problema.",
    update_type: "evidence",
    published: true,
    published_at: "2026-03-17T11:00:00.000Z",
    featured: false,
    sort_order: 2,
    created_at: "2026-03-17T11:00:00.000Z",
    updated_at: "2026-03-17T11:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "dossier-update-3",
    dossier_id: "dossier-1",
    title: "Seguimos recebendo pistas sobre o ponto de maior impacto",
    slug: "seguimos-recebendo-pistas-ponto-maior-impacto",
    excerpt: "Quem tiver relato, documento ou foto pode ajudar a fechar a próxima etapa.",
    body:
      "Há uma etapa ainda em aberto sobre a concentração do impacto no território. Se você tem documento, relato ou material visual, o canal de envio continua disponível para cruzamento editorial.",
    update_type: "call",
    published: true,
    published_at: "2026-03-19T09:00:00.000Z",
    featured: false,
    sort_order: 3,
    created_at: "2026-03-19T09:00:00.000Z",
    updated_at: "2026-03-19T09:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "dossier-update-4",
    dossier_id: "dossier-2",
    title: "Nova fala de trabalhador reforça a normalização do risco",
    slug: "nova-fala-trabalhador-normalizacao-risco",
    excerpt: "A rotina do turno continua aparecendo como zona de pressão contínua.",
    body:
      "O dossiê recebeu um novo relato que mostra como a pressão do turno não aparece apenas no acidente: ela se espalha pela preparação, pela expectativa de produção e pela gestão do tempo de trabalho.",
    update_type: "monitoring",
    published: true,
    published_at: "2026-03-18T14:20:00.000Z",
    featured: true,
    sort_order: 1,
    created_at: "2026-03-18T14:20:00.000Z",
    updated_at: "2026-03-18T14:20:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "dossier-update-5",
    dossier_id: "dossier-2",
    title: "Correção de trecho sobre a data de um registro",
    slug: "correcao-trecho-data-registro",
    excerpt: "Um registro anterior foi corrigido para manter a cronologia fiel.",
    body:
      "Corrigimos a data de um trecho relacionado ao arquivo de apoio. A mudança não altera a hipótese central; ela apenas ajusta a leitura temporal para evitar ruído e preservar precisão editorial.",
    update_type: "correction",
    published: true,
    published_at: "2026-03-19T10:10:00.000Z",
    featured: false,
    sort_order: 2,
    created_at: "2026-03-19T10:10:00.000Z",
    updated_at: "2026-03-19T10:10:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "dossier-update-6",
    dossier_id: "dossier-3",
    title: "A investigação foi concluída, mas o desgaste urbano continua",
    slug: "investigacao-concluida-desgaste-urbano-continua",
    excerpt: "O dossiê fecha uma etapa e deixa o arquivo aberto para desdobramentos futuros.",
    body:
      "Este recorte chegou a uma conclusão editorial sobre o estado do abandono em partes da cidade. Ainda assim, o tema continua vivo como arquivo: novos documentos ou relatos podem reabrir partes do percurso em outra linha investigativa.",
    update_type: "note",
    published: true,
    published_at: "2026-03-16T15:00:00.000Z",
    featured: true,
    sort_order: 1,
    created_at: "2026-03-16T15:00:00.000Z",
    updated_at: "2026-03-16T15:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
];
