import type { MemoryItem } from "@/lib/memory/types";

export const memoryMockItems: MemoryItem[] = [
  {
    id: "memory-1",
    slug: "greve-e-fabrica",
    title: "Greve, fábrica e bairro: quando a cidade aprendeu a se organizar",
    excerpt:
      "Um recorte sobre a formação operária da cidade e as redes populares que surgiram entre trabalho, rua e sindicato.",
    body:
      "Volta Redonda se organiza na contramão do silêncio.\n\nA memória operária não é peça de museu. Ela vive nos bairros, nas greves, nas conversas de portão e nas formas de se defender do apagamento oficial.",
    memory_type: "landmark",
    memory_collection: "cidade-operaria",
    collection_slug: "cidade-operaria",
    collection_title: "Cidade operária",
    period_label: "Anos 1940-1970",
    year_start: 1946,
    year_end: 1978,
    place_label: "Vila Santa Cecília",
    source_note: "Síntese editorial a partir de relatos, recortes e documentação pública.",
    archive_status: "featured",
    editorial_status: "published",
    published: true,
    published_at: "2026-03-19T12:00:00.000Z",
    featured: true,
    highlight_in_memory: true,
    timeline_rank: 1,
    related_editorial_slug: "o-que-sobrou-da-promessa-industrial",
    related_series_slug: "memoria-operaria",
    cover_image_url: "/editorial/covers/arquivo-inicial.svg",
    cover_image_path: null,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "memory-2",
    slug: "poeira-e-fumaca",
    title: "Poeira e fumaça: a cidade respirada por dentro",
    excerpt:
      "Recorte sobre poluição, rotina industrial e os efeitos cotidianos do entorno produtivo sobre bairros inteiros.",
    body:
      "O ar também escreve história.\n\nQuando a fumaça vira costume, a cidade precisa reaprender a nomear o que sente no pulmão, nas janelas e nas roupas estendidas.",
    memory_type: "document",
    memory_collection: "poluicao-e-industria",
    collection_slug: "poluicao-e-industria",
    collection_title: "Poluição e indústria",
    period_label: "Décadas recentes",
    year_start: 1990,
    year_end: null,
    place_label: "Aterrado e entorno industrial",
    source_note: "Recorte de memória pública e observação territorial.",
    archive_status: "active",
    editorial_status: "published",
    published: true,
    published_at: "2026-03-19T12:00:00.000Z",
    featured: true,
    highlight_in_memory: true,
    timeline_rank: 2,
    related_editorial_slug: "ar-poeira-e-pressao",
    related_series_slug: "poluicao-e-csn",
    cover_image_url: null,
    cover_image_path: null,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "memory-3",
    slug: "acidente-e-turno",
    title: "Acidente e turno: o corpo como registro do trabalho",
    excerpt:
      "Memória de lesões, desgaste e normalização do risco no cotidiano laboral da cidade operária.",
    body:
      "O trabalho deixa marca antes de virar estatística.\n\nEntre turno, deslocamento e pressão por produção, o acidente aparece como parte do sistema, não como exceção isolada.",
    memory_type: "story",
    memory_collection: "trabalho-e-acidentes",
    collection_slug: "trabalho-e-acidentes",
    collection_title: "Trabalho e acidentes",
    period_label: "Anos 2000-2020",
    year_start: 2004,
    year_end: 2020,
    place_label: "Volta Grande",
    source_note: "Relato sintético para demonstrar a relação entre memória e pauta.",
    archive_status: "active",
    editorial_status: "ready",
    published: false,
    published_at: null,
    featured: false,
    highlight_in_memory: false,
    timeline_rank: 3,
    related_editorial_slug: "turno-risco-e-lesao",
    related_series_slug: "trabalho-e-acidentes",
    cover_image_url: null,
    cover_image_path: null,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "memory-4",
    slug: "apagamentos-do-centro",
    title: "Apagamentos do centro: o que some quando a cidade se reescreve",
    excerpt:
      "Marcos, demolições, rebatismos e apagamentos da paisagem urbana sob a linguagem da modernização.",
    body:
      "Toda reforma deixa uma disputa de memória.\n\nNo centro, o que some costuma desaparecer com nome técnico, mas continua existindo na lembrança de quem viveu a transição.",
    memory_type: "event",
    memory_collection: "apagamentos-e-disputas",
    collection_slug: "apagamentos-e-disputas",
    collection_title: "Apagamentos e disputas",
    period_label: "Requalificações urbanas",
    year_start: 1985,
    year_end: 2025,
    place_label: "Centro",
    source_note: "Linha editorial aberta para cruzar documento, relato e arquivo visual.",
    archive_status: "archived",
    editorial_status: "archived",
    published: false,
    published_at: null,
    featured: false,
    highlight_in_memory: false,
    timeline_rank: 4,
    related_editorial_slug: "linha-tarifa-e-espera",
    related_series_slug: "cidade-e-abandono",
    cover_image_url: null,
    cover_image_path: null,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
];
