import type { PlaceHub, PlaceHubLink } from "@/lib/territories/types";

export const placeHubMockItems: PlaceHub[] = [
  {
    id: "place-hub-1",
    title: "Cidade operária",
    slug: "cidade-operaria",
    excerpt: "Bairro e memória de origem da cidade do trabalho.",
    description:
      "Cidade operária funciona como porta de entrada para entender como a cidade foi moldada entre fábrica, bairro e conflito público.",
    lead_question: "Como o bairro operário ainda organiza a cidade de hoje?",
    place_type: "bairro",
    parent_place_slug: null,
    territory_label: "Vila Santa Cecília",
    address_label: "Volta Redonda, RJ",
    latitude: null,
    longitude: null,
    cover_image_url: "/archive/assets/acervo-foto-oficina.svg",
    featured: true,
    public_visibility: true,
    status: "active",
    sort_order: 1,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "place-hub-2",
    title: "CSN e entorno",
    slug: "csn-e-entorno",
    excerpt: "Usina e zona crítica para ler ar, fumaça e custo ambiental.",
    description:
      "O entorno da CSN ajuda a entender como indústria, bairro e saúde pública continuam acoplados no cotidiano da cidade.",
    lead_question: "Quem respira o custo do entorno industrial?",
    place_type: "usina",
    parent_place_slug: null,
    territory_label: "Cidade e entorno industrial",
    address_label: "Volta Redonda, RJ",
    latitude: null,
    longitude: null,
    cover_image_url: "/archive/assets/acervo-recorte-jornal.svg",
    featured: true,
    public_visibility: true,
    status: "monitoring",
    sort_order: 2,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "place-hub-3",
    title: "Hospital São João Batista",
    slug: "hospital-sao-joao-batista",
    excerpt: "Equipamento público onde saúde, fila e desgaste ganham forma concreta.",
    description:
      "O hospital organiza uma parte importante da leitura sobre saúde, atendimento e consequências do trabalho e do ambiente na vida urbana.",
    lead_question: "O que a cidade joga para dentro da fila do hospital?",
    place_type: "hospital",
    parent_place_slug: "cidade-operaria",
    territory_label: "Cidade do trabalho",
    address_label: "Volta Redonda, RJ",
    latitude: null,
    longitude: null,
    cover_image_url: "/archive/assets/acervo-relatorio.svg",
    featured: false,
    public_visibility: true,
    status: "active",
    sort_order: 3,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "place-hub-4",
    title: "Rodoviária Nova",
    slug: "rodoviaria-nova",
    excerpt: "Ponto de circulação e espera onde a cidade mostra sua fricção cotidiana.",
    description:
      "O terminal funciona como lugar de passagem, atraso e disputa por mobilidade, conectando abandono urbano e tempo roubado.",
    lead_question: "Quem paga o tempo da espera?",
    place_type: "ponto_critico",
    parent_place_slug: "cidade-operaria",
    territory_label: "Cidade em circulação",
    address_label: "Volta Redonda, RJ",
    latitude: null,
    longitude: null,
    cover_image_url: "/archive/assets/acervo-mapa.svg",
    featured: true,
    public_visibility: true,
    status: "monitoring",
    sort_order: 4,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "place-hub-5",
    title: "Praça Sávio Gama",
    slug: "praca-savio-gama",
    excerpt: "Marco urbano onde memória, circulação e apagamento se encontram.",
    description:
      "A praça ajuda a ler como centro, comércio e requalificação urbana reescrevem a paisagem da cidade e seus marcos públicos.",
    lead_question: "O que some quando o centro é refeito?",
    place_type: "praca",
    parent_place_slug: null,
    territory_label: "Centro de Volta Redonda",
    address_label: "Volta Redonda, RJ",
    latitude: null,
    longitude: null,
    cover_image_url: "/archive/assets/acervo-mapa.svg",
    featured: false,
    public_visibility: true,
    status: "archive",
    sort_order: 5,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "place-hub-6",
    title: "Vila Santa Cecília",
    slug: "vila-santa-cecilia",
    excerpt: "Lugar onde o bairro operário ainda organiza o mapa afetivo da cidade.",
    description:
      "A Vila ajuda a conectar arquitetura, trabalho, memória e vida de rua num mesmo percurso editorial.",
    lead_question: "O bairro ainda dita o ritmo da cidade?",
    place_type: "bairro",
    parent_place_slug: "cidade-operaria",
    territory_label: "Cidade operária",
    address_label: "Volta Redonda, RJ",
    latitude: null,
    longitude: null,
    cover_image_url: "/archive/assets/acervo-foto-oficina.svg",
    featured: false,
    public_visibility: true,
    status: "active",
    sort_order: 6,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
];

export const placeHubLinkMockItems: PlaceHubLink[] = [
  { id: "place-hub-link-1", place_hub_id: "place-hub-1", link_type: "editorial", link_key: "o-que-sobrou-da-promessa-industrial", link_role: "lead", timeline_year: 2026, timeline_label: "2026", timeline_note: "Pauta de entrada sobre bairro e promessa industrial.", featured: true, sort_order: 1, created_at: "2026-03-19T12:00:00.000Z", updated_at: "2026-03-19T12:00:00.000Z" },
  { id: "place-hub-link-2", place_hub_id: "place-hub-1", link_type: "dossier", link_key: "cidade-e-abandono", link_role: "context", timeline_year: 2026, timeline_label: "2026", timeline_note: "Dossiê que amarra o abandono urbano ao território.", featured: true, sort_order: 2, created_at: "2026-03-19T12:00:00.000Z", updated_at: "2026-03-19T12:00:00.000Z" },
  { id: "place-hub-link-3", place_hub_id: "place-hub-1", link_type: "memory", link_key: "greve-e-fabrica", link_role: "archive", timeline_year: 1950, timeline_label: "década de 1950", timeline_note: "Memória de origem operária do bairro.", featured: false, sort_order: 3, created_at: "2026-03-19T12:00:00.000Z", updated_at: "2026-03-19T12:00:00.000Z" },
  { id: "place-hub-link-4", place_hub_id: "place-hub-1", link_type: "archive", link_key: "archive-mock-1", link_role: "evidence", timeline_year: 1998, timeline_label: "1998", timeline_note: "Foto-base para ler a vida de bairro.", featured: false, sort_order: 4, created_at: "2026-03-19T12:00:00.000Z", updated_at: "2026-03-19T12:00:00.000Z" },
  { id: "place-hub-link-5", place_hub_id: "place-hub-1", link_type: "campaign", link_key: "respira-volta-redonda", link_role: "followup", timeline_year: 2026, timeline_label: "2026", timeline_note: "Chamado que recorta o entorno industrial da cidade.", featured: false, sort_order: 5, created_at: "2026-03-19T12:00:00.000Z", updated_at: "2026-03-19T12:00:00.000Z" },
  { id: "place-hub-link-6", place_hub_id: "place-hub-1", link_type: "impact", link_key: "arquivo-que-volta-a-falar", link_role: "followup", timeline_year: 2026, timeline_label: "2026", timeline_note: "Consequência pública ligada à memória do bairro.", featured: false, sort_order: 6, created_at: "2026-03-19T12:00:00.000Z", updated_at: "2026-03-19T12:00:00.000Z" },
  { id: "place-hub-link-7", place_hub_id: "place-hub-2", link_type: "editorial", link_key: "ar-poeira-e-pressao", link_role: "lead", timeline_year: 2026, timeline_label: "2026", timeline_note: "Pauta de entrada sobre ar e fumaça.", featured: true, sort_order: 1, created_at: "2026-03-19T12:00:00.000Z", updated_at: "2026-03-19T12:00:00.000Z" },
  { id: "place-hub-link-8", place_hub_id: "place-hub-2", link_type: "dossier", link_key: "ar-fumaca-e-rotina-industrial", link_role: "context", timeline_year: 2026, timeline_label: "2026", timeline_note: "Dossiê de base para a disputa do ar.", featured: true, sort_order: 2, created_at: "2026-03-19T12:00:00.000Z", updated_at: "2026-03-19T12:00:00.000Z" },
  { id: "place-hub-link-9", place_hub_id: "place-hub-2", link_type: "memory", link_key: "poeira-e-fumaca", link_role: "archive", timeline_year: 1997, timeline_label: "fim dos anos 1990", timeline_note: "Memória territorial da fumaça recorrente.", featured: false, sort_order: 3, created_at: "2026-03-19T12:00:00.000Z", updated_at: "2026-03-19T12:00:00.000Z" },
  { id: "place-hub-link-10", place_hub_id: "place-hub-2", link_type: "archive", link_key: "archive-mock-2", link_role: "evidence", timeline_year: 2001, timeline_label: "2001", timeline_note: "Recorte documental ligado ao tema ambiental.", featured: false, sort_order: 4, created_at: "2026-03-19T12:00:00.000Z", updated_at: "2026-03-19T12:00:00.000Z" },
  { id: "place-hub-link-11", place_hub_id: "place-hub-2", link_type: "campaign", link_key: "respira-volta-redonda", link_role: "followup", timeline_year: 2026, timeline_label: "2026", timeline_note: "Chamado público que mantém a frente ativa.", featured: false, sort_order: 5, created_at: "2026-03-19T12:00:00.000Z", updated_at: "2026-03-19T12:00:00.000Z" },
  { id: "place-hub-link-12", place_hub_id: "place-hub-2", link_type: "impact", link_key: "respira-volta-redonda", link_role: "followup", timeline_year: 2026, timeline_label: "2026", timeline_note: "Efeito público observado da mobilização.", featured: false, sort_order: 6, created_at: "2026-03-19T12:00:00.000Z", updated_at: "2026-03-19T12:00:00.000Z" },
  { id: "place-hub-link-13", place_hub_id: "place-hub-3", link_type: "editorial", link_key: "turno-risco-e-lesao", link_role: "lead", timeline_year: 2026, timeline_label: "2026", timeline_note: "Pauta de entrada sobre risco e lesão.", featured: true, sort_order: 1, created_at: "2026-03-19T12:00:00.000Z", updated_at: "2026-03-19T12:00:00.000Z" },
  { id: "place-hub-link-14", place_hub_id: "place-hub-3", link_type: "dossier", link_key: "trabalho-ferido-corpo-insistente", link_role: "context", timeline_year: 2026, timeline_label: "2026", timeline_note: "Dossiê que organiza o caso de trabalho.", featured: true, sort_order: 2, created_at: "2026-03-19T12:00:00.000Z", updated_at: "2026-03-19T12:00:00.000Z" },
  { id: "place-hub-link-15", place_hub_id: "place-hub-3", link_type: "memory", link_key: "acidente-e-turno", link_role: "archive", timeline_year: 2004, timeline_label: "2004", timeline_note: "Memória do corpo em turno e acidente.", featured: false, sort_order: 3, created_at: "2026-03-19T12:00:00.000Z", updated_at: "2026-03-19T12:00:00.000Z" },
  { id: "place-hub-link-16", place_hub_id: "place-hub-3", link_type: "archive", link_key: "archive-mock-3", link_role: "evidence", timeline_year: 2006, timeline_label: "2006", timeline_note: "Documento-base para o percurso do lugar.", featured: false, sort_order: 4, created_at: "2026-03-19T12:00:00.000Z", updated_at: "2026-03-19T12:00:00.000Z" },
  { id: "place-hub-link-17", place_hub_id: "place-hub-3", link_type: "impact", link_key: "trabalho-sob-observacao", link_role: "followup", timeline_year: 2026, timeline_label: "2026", timeline_note: "Impacto de monitoramento do caso.", featured: false, sort_order: 5, created_at: "2026-03-19T12:00:00.000Z", updated_at: "2026-03-19T12:00:00.000Z" },
  { id: "place-hub-link-18", place_hub_id: "place-hub-4", link_type: "editorial", link_key: "linha-tarifa-e-espera", link_role: "lead", timeline_year: 2026, timeline_label: "2026", timeline_note: "Pauta sobre espera e mobilidade no terminal.", featured: true, sort_order: 1, created_at: "2026-03-19T12:00:00.000Z", updated_at: "2026-03-19T12:00:00.000Z" },
  { id: "place-hub-link-19", place_hub_id: "place-hub-4", link_type: "dossier", link_key: "cidade-e-abandono", link_role: "context", timeline_year: 2026, timeline_label: "2026", timeline_note: "Dossiê sobre abandono urbano e tempo roubado.", featured: true, sort_order: 2, created_at: "2026-03-19T12:00:00.000Z", updated_at: "2026-03-19T12:00:00.000Z" },
  { id: "place-hub-link-20", place_hub_id: "place-hub-4", link_type: "campaign", link_key: "trabalho-sob-observacao", link_role: "followup", timeline_year: 2026, timeline_label: "2026", timeline_note: "Chamado que ajuda a puxar atenção pública para o deslocamento e o desgaste.", featured: false, sort_order: 3, created_at: "2026-03-19T12:00:00.000Z", updated_at: "2026-03-19T12:00:00.000Z" },
  { id: "place-hub-link-21", place_hub_id: "place-hub-5", link_type: "memory", link_key: "apagamentos-do-centro", link_role: "lead", timeline_year: 1985, timeline_label: "requalificações urbanas", timeline_note: "Memória que ajuda a ler apagamentos no centro.", featured: true, sort_order: 1, created_at: "2026-03-19T12:00:00.000Z", updated_at: "2026-03-19T12:00:00.000Z" },
  { id: "place-hub-link-22", place_hub_id: "place-hub-5", link_type: "archive", link_key: "archive-mock-4", link_role: "evidence", timeline_year: 2010, timeline_label: "2010", timeline_note: "Mapa e recorte que sustentam a leitura do lugar.", featured: false, sort_order: 2, created_at: "2026-03-19T12:00:00.000Z", updated_at: "2026-03-19T12:00:00.000Z" },
  { id: "place-hub-link-23", place_hub_id: "place-hub-5", link_type: "hub", link_key: "cidade-e-abandono", link_role: "context", timeline_year: 2026, timeline_label: "2026", timeline_note: "Eixo que organiza o tema urbano do lugar.", featured: false, sort_order: 3, created_at: "2026-03-19T12:00:00.000Z", updated_at: "2026-03-19T12:00:00.000Z" },
  { id: "place-hub-link-24", place_hub_id: "place-hub-6", link_type: "editorial", link_key: "o-que-sobrou-da-promessa-industrial", link_role: "lead", timeline_year: 2026, timeline_label: "2026", timeline_note: "Pauta que abre o território do bairro operário.", featured: true, sort_order: 1, created_at: "2026-03-19T12:00:00.000Z", updated_at: "2026-03-19T12:00:00.000Z" },
  { id: "place-hub-link-25", place_hub_id: "place-hub-6", link_type: "memory", link_key: "greve-e-fabrica", link_role: "context", timeline_year: 1950, timeline_label: "década de 1950", timeline_note: "Memória de organização popular no bairro.", featured: false, sort_order: 2, created_at: "2026-03-19T12:00:00.000Z", updated_at: "2026-03-19T12:00:00.000Z" },
  { id: "place-hub-link-26", place_hub_id: "place-hub-6", link_type: "impact", link_key: "arquivo-que-volta-a-falar", link_role: "followup", timeline_year: 2026, timeline_label: "2026", timeline_note: "Consequência pública ligada à memória reativada.", featured: false, sort_order: 3, created_at: "2026-03-19T12:00:00.000Z", updated_at: "2026-03-19T12:00:00.000Z" },
];
