import type { TimelineHighlight, TimelineHighlightLink } from "@/lib/timeline/highlights";

export const timelineHighlightMockItems: TimelineHighlight[] = [
  {
    id: "highlight-origin-city-operaria",
    title: "Origem da cidade operária",
    slug: "origem-da-cidade-operaria",
    excerpt: "A cidade nasceu de indústria concentrada, planejamento duro e promessa de ordem. Este marco abre a leitura histórica do território.",
    description:
      "Um marco de origem para entender como a cidade foi moldada pela siderurgia, pela disciplina do trabalho e pela promessa de desenvolvimento que viria com o peso do chão industrial.",
    highlight_type: "origin",
    date_label: "1941",
    year_start: 1941,
    year_end: 1948,
    period_label: "Origem industrial",
    lead_question: "Quando a indústria moldou o chão urbano antes do discurso oficial?",
    cover_image_url: "/editorial/covers/arquivo-inicial.svg",
    featured: true,
    public_visibility: true,
    status: "active",
    sort_order: 1,
    created_at: "2026-03-20T12:00:00.000Z",
    updated_at: "2026-03-20T12:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "highlight-rupture-promessa-abandono",
    title: "Ruptura entre promessa e abandono",
    slug: "ruptura-entre-promessa-e-abandono",
    excerpt: "A distância entre desenvolvimento prometido e cidade vivida vira ruptura pública.",
    description:
      "Este marco lê a virada em que a promessa industrial deixa de bastar e o abandono urbano passa a aparecer como experiência cotidiana. É a fissura que reorganiza a leitura da cidade.",
    highlight_type: "rupture",
    date_label: "1990–2004",
    year_start: 1990,
    year_end: 2004,
    period_label: "Reconfiguração",
    lead_question: "Quando o discurso de desenvolvimento começou a perder lastro na cidade vivida?",
    cover_image_url: "/editorial/covers/arquivo-inicial.svg",
    featured: true,
    public_visibility: true,
    status: "active",
    sort_order: 2,
    created_at: "2026-03-20T12:00:00.000Z",
    updated_at: "2026-03-20T12:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "highlight-recurrence-poeira",
    title: "A poeira que volta",
    slug: "a-poeira-que-volta",
    excerpt: "Poluição, desgaste e rotina industrial reaparecem com novas medições e velhas consequências.",
    description:
      "Um marco de recorrência para mostrar como o tema ambiental retorna em ciclos, atravessando campanhas, relatos, documentos e o corpo da cidade.",
    highlight_type: "recurrence",
    date_label: "2018–2026",
    year_start: 2018,
    year_end: 2026,
    period_label: "Retorno recorrente",
    lead_question: "O que faz o problema voltar com novas formas e o mesmo peso?",
    cover_image_url: "/editorial/covers/arquivo-inicial.svg",
    featured: true,
    public_visibility: true,
    status: "monitoring",
    sort_order: 3,
    created_at: "2026-03-20T12:00:00.000Z",
    updated_at: "2026-03-20T12:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "highlight-consequence-impact-arquivo",
    title: "Quando o impacto vira arquivo",
    slug: "quando-o-impacto-vira-arquivo",
    excerpt: "Correção, documento e consequência: o arquivo volta a produzir efeito público.",
    description:
      "Um marco de consequência para ler como impacto, revisão e memória pública passam a se alimentar mutuamente quando a cidade reconhece o que mudou.",
    highlight_type: "consequence",
    date_label: "2024–2026",
    year_start: 2024,
    year_end: 2026,
    period_label: "Consequência pública",
    lead_question: "Quando o que foi observado começa a alterar o arquivo e a conversa pública?",
    cover_image_url: "/editorial/covers/arquivo-inicial.svg",
    featured: true,
    public_visibility: true,
    status: "active",
    sort_order: 4,
    created_at: "2026-03-20T12:00:00.000Z",
    updated_at: "2026-03-20T12:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
];

export const timelineHighlightLinkMockItems: TimelineHighlightLink[] = [
  {
    id: "highlight-link-1",
    timeline_highlight_id: "highlight-origin-city-operaria",
    link_type: "editorial",
    link_key: "o-que-sobrou-da-promessa-industrial",
    link_role: "lead",
    timeline_year: 1941,
    timeline_label: "1941",
    timeline_note: "Pauta que ajuda a abrir a leitura da origem industrial.",
    featured: true,
    sort_order: 1,
    created_at: "2026-03-20T12:00:00.000Z",
    updated_at: "2026-03-20T12:00:00.000Z",
  },
  {
    id: "highlight-link-2",
    timeline_highlight_id: "highlight-origin-city-operaria",
    link_type: "memory",
    link_key: "greve-e-fabrica",
    link_role: "evidence",
    timeline_year: 1941,
    timeline_label: "Memória operária",
    timeline_note: "Relato de base para compreender a origem do conflito.",
    featured: false,
    sort_order: 2,
    created_at: "2026-03-20T12:00:00.000Z",
    updated_at: "2026-03-20T12:00:00.000Z",
  },
  {
    id: "highlight-link-3",
    timeline_highlight_id: "highlight-origin-city-operaria",
    link_type: "archive",
    link_key: "archive-mock-4",
    link_role: "archive",
    timeline_year: 1941,
    timeline_label: "Arquivo de base",
    timeline_note: "Documento preservado que sustenta a leitura do marco.",
    featured: false,
    sort_order: 3,
    created_at: "2026-03-20T12:00:00.000Z",
    updated_at: "2026-03-20T12:00:00.000Z",
  },
  {
    id: "highlight-link-4",
    timeline_highlight_id: "highlight-origin-city-operaria",
    link_type: "territory",
    link_key: "cidade-operaria",
    link_role: "context",
    timeline_year: 1941,
    timeline_label: "Cidade operária",
    timeline_note: "Lugar onde a origem se condensa como espaço vivido.",
    featured: false,
    sort_order: 4,
    created_at: "2026-03-20T12:00:00.000Z",
    updated_at: "2026-03-20T12:00:00.000Z",
  },
  {
    id: "highlight-link-5",
    timeline_highlight_id: "highlight-origin-city-operaria",
    link_type: "actor",
    link_key: "companhia-siderurgica-nacional",
    link_role: "context",
    timeline_year: 1941,
    timeline_label: "CSN",
    timeline_note: "Ator estrutural que molda a origem da cidade.",
    featured: false,
    sort_order: 5,
    created_at: "2026-03-20T12:00:00.000Z",
    updated_at: "2026-03-20T12:00:00.000Z",
  },
  {
    id: "highlight-link-6",
    timeline_highlight_id: "highlight-rupture-promessa-abandono",
    link_type: "editorial",
    link_key: "linha-tarifa-e-espera",
    link_role: "lead",
    timeline_year: 2004,
    timeline_label: "2004",
    timeline_note: "Pauta que explicita a virada entre promessa e abandono.",
    featured: true,
    sort_order: 1,
    created_at: "2026-03-20T12:00:00.000Z",
    updated_at: "2026-03-20T12:00:00.000Z",
  },
  {
    id: "highlight-link-7",
    timeline_highlight_id: "highlight-rupture-promessa-abandono",
    link_type: "dossier",
    link_key: "cidade-e-abandono",
    link_role: "context",
    timeline_year: 2004,
    timeline_label: "Dossiê Cidade e abandono",
    timeline_note: "Caso que organiza a ruptura urbana em percurso público.",
    featured: false,
    sort_order: 2,
    created_at: "2026-03-20T12:00:00.000Z",
    updated_at: "2026-03-20T12:00:00.000Z",
  },
  {
    id: "highlight-link-8",
    timeline_highlight_id: "highlight-rupture-promessa-abandono",
    link_type: "pattern",
    link_key: "centro-espera-e-abandono",
    link_role: "evidence",
    timeline_year: 2004,
    timeline_label: "Padrão recorrente",
    timeline_note: "Leitura estrutural da ruptura na cidade.",
    featured: false,
    sort_order: 3,
    created_at: "2026-03-20T12:00:00.000Z",
    updated_at: "2026-03-20T12:00:00.000Z",
  },
  {
    id: "highlight-link-9",
    timeline_highlight_id: "highlight-rupture-promessa-abandono",
    link_type: "territory",
    link_key: "vila-santa-cecilia",
    link_role: "context",
    timeline_year: 2004,
    timeline_label: "Vila Santa Cecília",
    timeline_note: "Território que mostra a ruptura no cotidiano.",
    featured: false,
    sort_order: 4,
    created_at: "2026-03-20T12:00:00.000Z",
    updated_at: "2026-03-20T12:00:00.000Z",
  },
  {
    id: "highlight-link-10",
    timeline_highlight_id: "highlight-rupture-promessa-abandono",
    link_type: "campaign",
    link_key: "trabalho-sob-observacao",
    link_role: "followup",
    timeline_year: 2004,
    timeline_label: "Campanha conectada",
    timeline_note: "Chamado público que reabre a ruptura em outra chave.",
    featured: false,
    sort_order: 5,
    created_at: "2026-03-20T12:00:00.000Z",
    updated_at: "2026-03-20T12:00:00.000Z",
  },
  {
    id: "highlight-link-11",
    timeline_highlight_id: "highlight-recurrence-poeira",
    link_type: "editorial",
    link_key: "ar-poeira-e-pressao",
    link_role: "lead",
    timeline_year: 2018,
    timeline_label: "2018",
    timeline_note: "Pauta que mantém a frente ambiental em circulação.",
    featured: true,
    sort_order: 1,
    created_at: "2026-03-20T12:00:00.000Z",
    updated_at: "2026-03-20T12:00:00.000Z",
  },
  {
    id: "highlight-link-12",
    timeline_highlight_id: "highlight-recurrence-poeira",
    link_type: "campaign",
    link_key: "respira-volta-redonda",
    link_role: "context",
    timeline_year: 2018,
    timeline_label: "Campanha Respira",
    timeline_note: "Mobilização que condensou a frente ambiental.",
    featured: true,
    sort_order: 2,
    created_at: "2026-03-20T12:00:00.000Z",
    updated_at: "2026-03-20T12:00:00.000Z",
  },
  {
    id: "highlight-link-13",
    timeline_highlight_id: "highlight-recurrence-poeira",
    link_type: "impact",
    link_key: "respira-volta-redonda",
    link_role: "evidence",
    timeline_year: 2020,
    timeline_label: "Impacto observado",
    timeline_note: "Efeito público que volta a aparecer em novas formas.",
    featured: false,
    sort_order: 3,
    created_at: "2026-03-20T12:00:00.000Z",
    updated_at: "2026-03-20T12:00:00.000Z",
  },
  {
    id: "highlight-link-14",
    timeline_highlight_id: "highlight-recurrence-poeira",
    link_type: "dossier",
    link_key: "ar-fumaca-e-rotina-industrial",
    link_role: "context",
    timeline_year: 2018,
    timeline_label: "Dossiê ambiental",
    timeline_note: "Caso que organiza a recorrência da poluição.",
    featured: false,
    sort_order: 4,
    created_at: "2026-03-20T12:00:00.000Z",
    updated_at: "2026-03-20T12:00:00.000Z",
  },
  {
    id: "highlight-link-15",
    timeline_highlight_id: "highlight-recurrence-poeira",
    link_type: "territory",
    link_key: "csn-e-entorno",
    link_role: "context",
    timeline_year: 2018,
    timeline_label: "CSN e entorno",
    timeline_note: "Território onde a recorrência se torna visível.",
    featured: false,
    sort_order: 5,
    created_at: "2026-03-20T12:00:00.000Z",
    updated_at: "2026-03-20T12:00:00.000Z",
  },
  {
    id: "highlight-link-16",
    timeline_highlight_id: "highlight-recurrence-poeira",
    link_type: "actor",
    link_key: "companhia-siderurgica-nacional",
    link_role: "context",
    timeline_year: 2018,
    timeline_label: "CSN",
    timeline_note: "Ator recorrente da frente ambiental.",
    featured: false,
    sort_order: 6,
    created_at: "2026-03-20T12:00:00.000Z",
    updated_at: "2026-03-20T12:00:00.000Z",
  },
  {
    id: "highlight-link-17",
    timeline_highlight_id: "highlight-recurrence-poeira",
    link_type: "pattern",
    link_key: "a-poeira-que-volta",
    link_role: "archive",
    timeline_year: 2018,
    timeline_label: "Padrão de recorrência",
    timeline_note: "Síntese estrutural do retorno do tema.",
    featured: false,
    sort_order: 7,
    created_at: "2026-03-20T12:00:00.000Z",
    updated_at: "2026-03-20T12:00:00.000Z",
  },
  {
    id: "highlight-link-18",
    timeline_highlight_id: "highlight-consequence-impact-arquivo",
    link_type: "impact",
    link_key: "arquivo-que-volta-a-falar",
    link_role: "lead",
    timeline_year: 2024,
    timeline_label: "Impacto e arquivo",
    timeline_note: "O impacto reconfigura a leitura pública do arquivo.",
    featured: true,
    sort_order: 1,
    created_at: "2026-03-20T12:00:00.000Z",
    updated_at: "2026-03-20T12:00:00.000Z",
  },
  {
    id: "highlight-link-19",
    timeline_highlight_id: "highlight-consequence-impact-arquivo",
    link_type: "dossier",
    link_key: "investigacao-concluida-desgaste-urbano-continua",
    link_role: "context",
    timeline_year: 2024,
    timeline_label: "Dossiê concluído",
    timeline_note: "O caso segue vivo como consequência pública.",
    featured: false,
    sort_order: 2,
    created_at: "2026-03-20T12:00:00.000Z",
    updated_at: "2026-03-20T12:00:00.000Z",
  },
  {
    id: "highlight-link-20",
    timeline_highlight_id: "highlight-consequence-impact-arquivo",
    link_type: "dossier_update",
    link_key: "investigacao-concluida-desgaste-urbano-continua",
    link_role: "followup",
    timeline_year: 2024,
    timeline_label: "Atualização do dossiê",
    timeline_note: "Atualização pública que mostra a consequência do trabalho editorial.",
    featured: false,
    sort_order: 3,
    created_at: "2026-03-20T12:00:00.000Z",
    updated_at: "2026-03-20T12:00:00.000Z",
  },
  {
    id: "highlight-link-21",
    timeline_highlight_id: "highlight-consequence-impact-arquivo",
    link_type: "memory",
    link_key: "apagamentos-do-centro",
    link_role: "archive",
    timeline_year: 2024,
    timeline_label: "Memória de base",
    timeline_note: "Memória urbana que reabre a leitura da consequência.",
    featured: false,
    sort_order: 4,
    created_at: "2026-03-20T12:00:00.000Z",
    updated_at: "2026-03-20T12:00:00.000Z",
  },
  {
    id: "highlight-link-22",
    timeline_highlight_id: "highlight-consequence-impact-arquivo",
    link_type: "edition",
    link_key: "arquivo-que-volta-a-falar",
    link_role: "followup",
    timeline_year: 2024,
    timeline_label: "Edição de circulação",
    timeline_note: "Síntese editorial que ajuda a espalhar a leitura.",
    featured: false,
    sort_order: 5,
    created_at: "2026-03-20T12:00:00.000Z",
    updated_at: "2026-03-20T12:00:00.000Z",
  },
  {
    id: "highlight-link-23",
    timeline_highlight_id: "highlight-consequence-impact-arquivo",
    link_type: "territory",
    link_key: "rodoviaria-nova",
    link_role: "context",
    timeline_year: 2024,
    timeline_label: "Rodoviária Nova",
    timeline_note: "Lugar onde a consequência volta a aparecer em forma urbana.",
    featured: false,
    sort_order: 6,
    created_at: "2026-03-20T12:00:00.000Z",
    updated_at: "2026-03-20T12:00:00.000Z",
  },
];
