import type { SharePack } from "@/lib/share-packs/types";

export const sharePackMockItems: SharePack[] = [
  {
    id: "share-pack-edition-1",
    content_type: "edicao",
    content_key: "edicao-do-momento-o-que-esta-quente-agora",
    title_override: "Edição do momento: o que está quente agora",
    short_summary: "Uma síntese curta do radar, das campanhas e do que ganhou peso na cidade.",
    share_caption: "Leia, compartilhe e acompanhe o que está em curso no VR Abandonada.",
    share_status: "published",
    cover_variant: "steel",
    preferred_format: "both",
    featured: true,
    public_visibility: true,
    sort_order: 1,
    created_at: "2026-03-20T12:00:00.000Z",
    updated_at: "2026-03-20T12:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "share-pack-campaign-1",
    content_type: "campanha",
    content_key: "respira-volta-redonda",
    title_override: "Respira Volta Redonda",
    short_summary: "Chamado público sobre ar, fumaça e consequência industrial no cotidiano da cidade.",
    share_caption: "Campanha em curso. Leia a linha, envie material e compartilhe a leitura.",
    share_status: "published",
    cover_variant: "ember",
    preferred_format: "square",
    featured: true,
    public_visibility: true,
    sort_order: 2,
    created_at: "2026-03-20T12:00:00.000Z",
    updated_at: "2026-03-20T12:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "share-pack-impact-1",
    content_type: "impacto",
    content_key: "respira-volta-redonda",
    title_override: "O que mudou em torno de respirar a cidade",
    short_summary: "Efeito público observado a partir da mobilização sobre poluição e pressão industrial.",
    share_caption: "Consequência pública também precisa circular. Compartilhe esta leitura.",
    share_status: "published",
    cover_variant: "concrete",
    preferred_format: "vertical",
    featured: false,
    public_visibility: true,
    sort_order: 3,
    created_at: "2026-03-20T12:00:00.000Z",
    updated_at: "2026-03-20T12:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "share-pack-dossier-1",
    content_type: "dossie",
    content_key: "ar-fumaca-e-rotina-industrial",
    title_override: "Ar, fumaça e rotina industrial",
    short_summary: "Dossiê vivo sobre poluição, corpo e custo cotidiano em volta da siderurgia.",
    share_caption: "Dossiê em curso. Leia, compartilhe e volte quando houver atualização.",
    share_status: "published",
    cover_variant: "night",
    preferred_format: "vertical",
    featured: false,
    public_visibility: true,
    sort_order: 4,
    created_at: "2026-03-20T12:00:00.000Z",
    updated_at: "2026-03-20T12:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "share-pack-pauta-1",
    content_type: "pauta",
    content_key: "ar-poeira-e-pressao",
    title_override: "Ar, poeira e pressão",
    short_summary: "Pauta de entrada sobre poluição e rotina industrial na cidade.",
    share_caption: "Leitura curta para circular a pauta e seguir a investigação.",
    share_status: "published",
    cover_variant: "concrete",
    preferred_format: "square",
    featured: false,
    public_visibility: true,
    sort_order: 5,
    created_at: "2026-03-20T12:00:00.000Z",
    updated_at: "2026-03-20T12:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "share-pack-pattern-1",
    content_type: "padrao",
    content_key: "a-poeira-que-volta",
    title_override: "A poeira que volta",
    short_summary: "Leitura estrutural sobre recorrência da poeira industrial na cidade.",
    share_caption: "Padrão de recorrência para leitura fora do site. Compartilhe o que se repete.",
    share_status: "published",
    cover_variant: "steel",
    preferred_format: "both",
    featured: false,
    public_visibility: true,
    sort_order: 6,
    created_at: "2026-03-20T12:00:00.000Z",
    updated_at: "2026-03-20T12:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
];
