import type { PatternRead, PatternReadLink } from "@/lib/patterns/types";

export const patternReadMockItems = [
  {
    id: "pattern-poeira-recorrente",
    title: "A poeira que volta",
    slug: "a-poeira-que-volta",
    excerpt: "A recorrência da fumaça e da poeira industrial organiza uma parte central da disputa pública da cidade.",
    description:
      "O padrão reúne casos, memória e impacto para mostrar que ar, fumaça e entorno industrial não aparecem como episódio isolado. Eles voltam como experiência territorial, corpo desgastado e conflito repetido.",
    pattern_type: "actor_recurrence",
    lead_question: "Por que a poeira industrial reaparece em pautas, memórias e efeitos públicos ao longo do tempo?",
    status: "active",
    cover_image_url: "/editorial/covers/arquivo-inicial.svg",
    featured: true,
    public_visibility: true,
    sort_order: 1,
    created_at: "2026-02-01T12:00:00.000Z",
    updated_at: "2026-02-01T12:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "pattern-centro-abandono",
    title: "Centro, espera e abandono",
    slug: "centro-espera-e-abandono",
    excerpt: "Obras, filas e fricções urbanas se repetem no centro e em pontos de passagem da cidade.",
    description:
      "Este padrão lê como o abandono urbano volta a aparecer nos mesmos lugares: centro, rodoviária, praças, circulação e serviços públicos. O conflito muda de nome, mas conserva a forma.",
    pattern_type: "territory_recurrence",
    lead_question: "O que o centro da cidade repete quando a resposta pública demora?",
    status: "monitoring",
    cover_image_url: "/archive/assets/acervo-mapa.svg",
    featured: true,
    public_visibility: true,
    sort_order: 2,
    created_at: "2026-02-01T12:10:00.000Z",
    updated_at: "2026-02-01T12:10:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "pattern-saude-desgaste",
    title: "Saúde, espera e desgaste",
    slug: "saude-espera-e-desgaste",
    excerpt: "Fila, distância e atendimento fragmentado voltam como padrão de consequência pública.",
    description:
      "O padrão organiza a repetição de pressão sobre a rede de saúde, mostrando como a espera se transforma em rotina e como o desgaste atravessa trabalho, ambiente e cuidado.",
    pattern_type: "institution_pattern",
    lead_question: "Quem absorve a espera quando a saúde vira rotina de desgaste?",
    status: "active",
    cover_image_url: "/archive/assets/acervo-relatorio.svg",
    featured: false,
    public_visibility: true,
    sort_order: 3,
    created_at: "2026-02-01T12:20:00.000Z",
    updated_at: "2026-02-01T12:20:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "pattern-arquivo-retorna",
    title: "O arquivo que retorna",
    slug: "o-arquivo-que-retorna",
    excerpt: "Memória, documento e correção reaparecem como consequência pública e não como nota lateral.",
    description:
      "Este padrão mostra como a reativação do arquivo produz movimento: correção, reposicionamento, novos vínculos e confirmação de que a memória da cidade não está encerrada.",
    pattern_type: "archive_pattern",
    lead_question: "Quando o arquivo volta a falar, o que se corrige e o que continua em disputa?",
    status: "archive",
    cover_image_url: "/archive/assets/acervo-foto-oficina.svg",
    featured: false,
    public_visibility: true,
    sort_order: 4,
    created_at: "2026-02-01T12:30:00.000Z",
    updated_at: "2026-02-01T12:30:00.000Z",
    created_by: null,
    updated_by: null,
  },
] satisfies PatternRead[];

export const patternReadLinkMockItems = [
  {
    id: "pattern-link-poeira-1",
    pattern_read_id: "pattern-poeira-recorrente",
    link_type: "actor",
    link_key: "companhia-siderurgica-nacional",
    link_role: "lead",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Ator recorrente que organiza a linha de conflito industrial.",
    featured: true,
    sort_order: 1,
    created_at: "2026-02-01T13:00:00.000Z",
    updated_at: "2026-02-01T13:00:00.000Z",
  },
  {
    id: "pattern-link-poeira-2",
    pattern_read_id: "pattern-poeira-recorrente",
    link_type: "territory",
    link_key: "csn-e-entorno",
    link_role: "context",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Entorno industrial como lugar onde a recorrência se torna visível.",
    featured: true,
    sort_order: 2,
    created_at: "2026-02-01T13:02:00.000Z",
    updated_at: "2026-02-01T13:02:00.000Z",
  },
  {
    id: "pattern-link-poeira-3",
    pattern_read_id: "pattern-poeira-recorrente",
    link_type: "editorial",
    link_key: "ar-poeira-e-pressao",
    link_role: "evidence",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Pauta que dá entrada pública ao tema.",
    featured: false,
    sort_order: 3,
    created_at: "2026-02-01T13:04:00.000Z",
    updated_at: "2026-02-01T13:04:00.000Z",
  },
  {
    id: "pattern-link-poeira-4",
    pattern_read_id: "pattern-poeira-recorrente",
    link_type: "dossier",
    link_key: "ar-fumaca-e-rotina-industrial",
    link_role: "context",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Dossiê que junta documentos e recorrência.",
    featured: false,
    sort_order: 4,
    created_at: "2026-02-01T13:06:00.000Z",
    updated_at: "2026-02-01T13:06:00.000Z",
  },
  {
    id: "pattern-link-poeira-5",
    pattern_read_id: "pattern-poeira-recorrente",
    link_type: "campaign",
    link_key: "respira-volta-redonda",
    link_role: "followup",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Chamado público que condensa a frente temporária.",
    featured: false,
    sort_order: 5,
    created_at: "2026-02-01T13:08:00.000Z",
    updated_at: "2026-02-01T13:08:00.000Z",
  },
  {
    id: "pattern-link-poeira-6",
    pattern_read_id: "pattern-poeira-recorrente",
    link_type: "impact",
    link_key: "respira-volta-redonda",
    link_role: "followup",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Efeito observado da mobilização.",
    featured: false,
    sort_order: 6,
    created_at: "2026-02-01T13:10:00.000Z",
    updated_at: "2026-02-01T13:10:00.000Z",
  },
  {
    id: "pattern-link-centro-1",
    pattern_read_id: "pattern-centro-abandono",
    link_type: "territory",
    link_key: "praca-savio-gama",
    link_role: "lead",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Marco urbano do centro e da disputa por forma pública.",
    featured: true,
    sort_order: 1,
    created_at: "2026-02-01T13:12:00.000Z",
    updated_at: "2026-02-01T13:12:00.000Z",
  },
  {
    id: "pattern-link-centro-2",
    pattern_read_id: "pattern-centro-abandono",
    link_type: "territory",
    link_key: "rodoviaria-nova",
    link_role: "evidence",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Lugar de fricção e espera repetida.",
    featured: true,
    sort_order: 2,
    created_at: "2026-02-01T13:14:00.000Z",
    updated_at: "2026-02-01T13:14:00.000Z",
  },
  {
    id: "pattern-link-centro-3",
    pattern_read_id: "pattern-centro-abandono",
    link_type: "editorial",
    link_key: "o-que-sobrou-da-promessa-industrial",
    link_role: "context",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Pauta que liga promessa e ruína urbana.",
    featured: false,
    sort_order: 3,
    created_at: "2026-02-01T13:16:00.000Z",
    updated_at: "2026-02-01T13:16:00.000Z",
  },
  {
    id: "pattern-link-centro-4",
    pattern_read_id: "pattern-centro-abandono",
    link_type: "dossier",
    link_key: "cidade-e-abandono",
    link_role: "context",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Dossiê que amarra o centro ao abandono urbano.",
    featured: false,
    sort_order: 4,
    created_at: "2026-02-01T13:18:00.000Z",
    updated_at: "2026-02-01T13:18:00.000Z",
  },
  {
    id: "pattern-link-centro-5",
    pattern_read_id: "pattern-centro-abandono",
    link_type: "campaign",
    link_key: "trabalho-sob-observacao",
    link_role: "followup",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Chamado que mantém o caso em circulação.",
    featured: false,
    sort_order: 5,
    created_at: "2026-02-01T13:20:00.000Z",
    updated_at: "2026-02-01T13:20:00.000Z",
  },
  {
    id: "pattern-link-centro-6",
    pattern_read_id: "pattern-centro-abandono",
    link_type: "impact",
    link_key: "arquivo-que-volta-a-falar",
    link_role: "followup",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Consequência pública ligada à memória reativada.",
    featured: false,
    sort_order: 6,
    created_at: "2026-02-01T13:22:00.000Z",
    updated_at: "2026-02-01T13:22:00.000Z",
  },
  {
    id: "pattern-link-saude-1",
    pattern_read_id: "pattern-saude-desgaste",
    link_type: "actor",
    link_key: "hospital-sao-joao-batista",
    link_role: "lead",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Equipamento público onde o desgaste vira rotina.",
    featured: true,
    sort_order: 1,
    created_at: "2026-02-01T13:24:00.000Z",
    updated_at: "2026-02-01T13:24:00.000Z",
  },
  {
    id: "pattern-link-saude-2",
    pattern_read_id: "pattern-saude-desgaste",
    link_type: "actor",
    link_key: "secretaria-municipal-de-saude",
    link_role: "context",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Área administrativa que responde ou falha em público.",
    featured: true,
    sort_order: 2,
    created_at: "2026-02-01T13:26:00.000Z",
    updated_at: "2026-02-01T13:26:00.000Z",
  },
  {
    id: "pattern-link-saude-3",
    pattern_read_id: "pattern-saude-desgaste",
    link_type: "editorial",
    link_key: "linha-tarifa-e-espera",
    link_role: "evidence",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Pauta que mostra a espera na cidade.",
    featured: false,
    sort_order: 3,
    created_at: "2026-02-01T13:28:00.000Z",
    updated_at: "2026-02-01T13:28:00.000Z",
  },
  {
    id: "pattern-link-saude-4",
    pattern_read_id: "pattern-saude-desgaste",
    link_type: "dossier",
    link_key: "trabalho-ferido-corpo-insistente",
    link_role: "context",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Dossiê que conecta trabalho e consequência física.",
    featured: false,
    sort_order: 4,
    created_at: "2026-02-01T13:30:00.000Z",
    updated_at: "2026-02-01T13:30:00.000Z",
  },
  {
    id: "pattern-link-saude-5",
    pattern_read_id: "pattern-saude-desgaste",
    link_type: "territory",
    link_key: "hospital-sao-joao-batista",
    link_role: "context",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Lugar onde a consequência pública se materializa.",
    featured: false,
    sort_order: 5,
    created_at: "2026-02-01T13:32:00.000Z",
    updated_at: "2026-02-01T13:32:00.000Z",
  },
  {
    id: "pattern-link-saude-6",
    pattern_read_id: "pattern-saude-desgaste",
    link_type: "impact",
    link_key: "trabalho-sob-observacao",
    link_role: "followup",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Impacto ligado à monitoria do caso.",
    featured: false,
    sort_order: 6,
    created_at: "2026-02-01T13:34:00.000Z",
    updated_at: "2026-02-01T13:34:00.000Z",
  },
  {
    id: "pattern-link-arquivo-1",
    pattern_read_id: "pattern-arquivo-retorna",
    link_type: "memory",
    link_key: "apagamentos-do-centro",
    link_role: "lead",
    timeline_year: 1985,
    timeline_label: "1985",
    timeline_note: "Memória que ajuda a ler a cidade em apagamento.",
    featured: true,
    sort_order: 1,
    created_at: "2026-02-01T13:36:00.000Z",
    updated_at: "2026-02-01T13:36:00.000Z",
  },
  {
    id: "pattern-link-arquivo-2",
    pattern_read_id: "pattern-arquivo-retorna",
    link_type: "archive",
    link_key: "archive-mock-1",
    link_role: "evidence",
    timeline_year: 1992,
    timeline_label: "1992",
    timeline_note: "Objeto de acervo que sustenta a leitura.",
    featured: true,
    sort_order: 2,
    created_at: "2026-02-01T13:38:00.000Z",
    updated_at: "2026-02-01T13:38:00.000Z",
  },
  {
    id: "pattern-link-arquivo-3",
    pattern_read_id: "pattern-arquivo-retorna",
    link_type: "collection",
    link_key: "apagamentos-da-memoria",
    link_role: "context",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Coleção pública que agrupa o recorte.",
    featured: false,
    sort_order: 3,
    created_at: "2026-02-01T13:40:00.000Z",
    updated_at: "2026-02-01T13:40:00.000Z",
  },
  {
    id: "pattern-link-arquivo-4",
    pattern_read_id: "pattern-arquivo-retorna",
    link_type: "hub",
    link_key: "memoria-de-volta-redonda",
    link_role: "archive",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Eixo de memória maior que enquadra o retorno do arquivo.",
    featured: false,
    sort_order: 4,
    created_at: "2026-02-01T13:42:00.000Z",
    updated_at: "2026-02-01T13:42:00.000Z",
  },
  {
    id: "pattern-link-arquivo-5",
    pattern_read_id: "pattern-arquivo-retorna",
    link_type: "editorial",
    link_key: "arquivo-que-volta-a-falar",
    link_role: "followup",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Pauta que reabre o arquivo para o presente.",
    featured: false,
    sort_order: 5,
    created_at: "2026-02-01T13:44:00.000Z",
    updated_at: "2026-02-01T13:44:00.000Z",
  },
  {
    id: "pattern-link-arquivo-6",
    pattern_read_id: "pattern-arquivo-retorna",
    link_type: "impact",
    link_key: "arquivo-que-volta-a-falar",
    link_role: "followup",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Consequência pública ligada à reativação do arquivo.",
    featured: false,
    sort_order: 6,
    created_at: "2026-02-01T13:46:00.000Z",
    updated_at: "2026-02-01T13:46:00.000Z",
  },
] satisfies PatternReadLink[];
