import type { EditorialItem } from "@/lib/editorial/types";

export const editorialMockItems: EditorialItem[] = [
  {
    id: "mock-1",
    intake_submission_id: null,
    title: "Linha, tarifa e espera: quem paga o tempo roubado da cidade?",
    slug: "linha-tarifa-e-espera",
    excerpt:
      "Uma leitura sobre transporte, atraso e custo cotidiano para quem depende da cidade em movimento.",
    body:
      "Volta Redonda opera com um relógio desigual.\n\nEnquanto alguns circulam rápido, outros acumulam atraso, custo e desgaste. O transporte se torna uma forma de disciplina urbana, e o corpo trabalhador paga o preço da espera.",
    category: "cidade",
    neighborhood: "Centro e bairros conectados",
    cover_image_url: null,
    published: true,
    published_at: "2026-03-19T12:00:00.000Z",
    editorial_status: "published",
    review_status: "reviewed",
    featured: true,
    publication_reason: "Texto inaugural da pauta pública do projeto.",
    sensitivity_check_passed: true,
    fact_check_note: "Síntese editorial validada para demonstração da base.",
    last_reviewed_at: "2026-03-19T12:00:00.000Z",
    last_reviewed_by: "equipe@vrabandonada.org",
    published_by: "equipe@vrabandonada.org",
    archived_reason: null,
    source_visibility_note: null,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "mock-2",
    intake_submission_id: null,
    title: "O que sobrou da promessa de desenvolvimento industrial?",
    slug: "o-que-sobrou-da-promessa-industrial",
    excerpt:
      "Memória operária e abandono urbano numa cidade que ainda carrega a marca da siderurgia.",
    body:
      "A cidade foi vendida como símbolo de progresso.\n\nO arquivo popular conta outra história: bairro desigual, infraestrutura cansada e uma lembrança constante de que desenvolvimento sem distribuição vira ruína organizada.",
    category: "memoria",
    neighborhood: "Vila Santa Cecília",
    cover_image_url: null,
    published: true,
    published_at: "2026-03-19T12:00:00.000Z",
    editorial_status: "published",
    review_status: "reviewed",
    featured: false,
    publication_reason: "Memória de acervo inicial publicada para demonstrar o arquivo vivo.",
    sensitivity_check_passed: true,
    fact_check_note: "Texto seguro para a vitrine pública de fundação.",
    last_reviewed_at: "2026-03-19T12:00:00.000Z",
    last_reviewed_by: "equipe@vrabandonada.org",
    published_by: "equipe@vrabandonada.org",
    archived_reason: null,
    source_visibility_note: null,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
];
