import type { EditorialItem } from "@/lib/editorial/types";

export const editorialMockItems: EditorialItem[] = [
  {
    id: "mock-1",
    intake_submission_id: null,
    title: "Linha, tarifa e espera: quem paga o tempo roubado da cidade?",
    slug: "linha-tarifa-e-espera",
    excerpt:
      "Uma leitura sobre transporte, atraso e custo cotidiano para quem depende da cidade em movimento.",
    body:
      "Volta Redonda opera com um relógio desigual.\n\nEnquanto alguns circulam rápido, outros acumulam atraso, custo e desgaste. O transporte se torna uma forma de disciplina urbana, e o corpo trabalhador paga o preço da espera.",
    category: "cidade",
    primary_tag: "transporte",
    secondary_tags: ["mobilidade", "tarifa", "tempo"],
    series_slug: "cidade-e-abandono",
    series_title: "Cidade e abandono",
    reading_time: 6,
    featured_order: 1,
    cover_variant: "ember",
    neighborhood: "Centro e bairros conectados",
    cover_image_url: null,
    cover_image_path: null,
    published: true,
    published_at: "2026-03-19T12:00:00.000Z",
    editorial_status: "published",
    review_status: "reviewed",
    featured: true,
    publication_reason: "Texto inaugural da pauta pública do projeto.",
    sensitivity_check_passed: true,
    fact_check_note: "Síntese editorial validada para demonstração da base.",
    last_reviewed_at: "2026-03-19T12:00:00.000Z",
    last_reviewed_by: "equipe@vrabandonada.org",
    published_by: "equipe@vrabandonada.org",
    archived_reason: null,
    source_visibility_note: null,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "mock-2",
    intake_submission_id: null,
    title: "O que sobrou da promessa de desenvolvimento industrial?",
    slug: "o-que-sobrou-da-promessa-industrial",
    excerpt:
      "Memória operária e abandono urbano numa cidade que ainda carrega a marca da siderurgia.",
    body:
      "A cidade foi vendida como símbolo de progresso.\n\nO arquivo popular conta outra história: bairro desigual, infraestrutura cansada e uma lembrança constante de que desenvolvimento sem distribuição vira ruína organizada.",
    category: "memoria",
    primary_tag: "memória",
    secondary_tags: ["siderurgia", "bairro", "arquivo"],
    series_slug: "memoria-operaria",
    series_title: "Memória operária",
    reading_time: 5,
    featured_order: 2,
    cover_variant: "steel",
    neighborhood: "Vila Santa Cecília",
    cover_image_url: null,
    cover_image_path: null,
    published: true,
    published_at: "2026-03-19T12:00:00.000Z",
    editorial_status: "published",
    review_status: "reviewed",
    featured: false,
    publication_reason: "Memória de acervo inicial publicada para demonstrar o arquivo vivo.",
    sensitivity_check_passed: true,
    fact_check_note: "Texto seguro para a vitrine pública de fundação.",
    last_reviewed_at: "2026-03-19T12:00:00.000Z",
    last_reviewed_by: "equipe@vrabandonada.org",
    published_by: "equipe@vrabandonada.org",
    archived_reason: null,
    source_visibility_note: null,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "mock-3",
    intake_submission_id: null,
    title: "Ar, poeira e pressão: o que a cidade respira junto com a fumaça?",
    slug: "ar-poeira-e-pressao",
    excerpt:
      "Poluição, rotina industrial e o efeito cumulativo de um território que vive entre chaminés e silêncio oficial.",
    body:
      "A contagem do dia passa pelo ar que entra no pulmão e pelo que a cidade prefere não nomear.\n\nEntre vento, poeira e expedientes, a vida cotidiana negocia com o entorno industrial sem pedir licença.",
    category: "ambiente",
    primary_tag: "poluição",
    secondary_tags: ["ar", "poeira", "rio"],
    series_slug: "poluicao-e-csn",
    series_title: "Poluição e CSN",
    reading_time: 7,
    featured_order: 3,
    cover_variant: "concrete",
    neighborhood: "Aterrado",
    cover_image_url: null,
    cover_image_path: null,
    published: true,
    published_at: "2026-03-19T12:00:00.000Z",
    editorial_status: "published",
    review_status: "reviewed",
    featured: false,
    publication_reason: "Linha ambiental publicada para mostrar a investigação em série.",
    sensitivity_check_passed: true,
    fact_check_note: "Texto revisado e seguro para exibição pública.",
    last_reviewed_at: "2026-03-19T12:00:00.000Z",
    last_reviewed_by: "equipe@vrabandonada.org",
    published_by: "equipe@vrabandonada.org",
    archived_reason: null,
    source_visibility_note: null,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "mock-4",
    intake_submission_id: null,
    title: "Turno, risco e lesão: quando o trabalho deixa marca no corpo",
    slug: "turno-risco-e-lesao",
    excerpt:
      "Uma pauta sobre acidente, desgaste e a naturalização da dor no cotidiano laboral da cidade operária.",
    body:
      "No chão de fábrica, no deslocamento e na espera, o risco deixa de ser exceção.\n\nA cidade aprende a tratar o machucado como ruído administrativo, quando deveria tratá-lo como evidência política.",
    category: "trabalho",
    primary_tag: "acidente",
    secondary_tags: ["segurança", "turno", "risco"],
    series_slug: "trabalho-e-acidentes",
    series_title: "Trabalho e acidentes",
    reading_time: 8,
    featured_order: 4,
    cover_variant: "night",
    neighborhood: "Volta Grande",
    cover_image_url: null,
    cover_image_path: null,
    published: true,
    published_at: "2026-03-19T12:00:00.000Z",
    editorial_status: "published",
    review_status: "reviewed",
    featured: false,
    publication_reason: "Fechamento da vitrine inicial com eixo de trabalho e risco.",
    sensitivity_check_passed: true,
    fact_check_note: "Conteúdo validado para a base editorial pública.",
    last_reviewed_at: "2026-03-19T12:00:00.000Z",
    last_reviewed_by: "equipe@vrabandonada.org",
    published_by: "equipe@vrabandonada.org",
    archived_reason: null,
    source_visibility_note: null,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
];


