import type { ThemeHub, ThemeHubLink } from "@/lib/hubs/types";

export const themeHubMockItems: ThemeHub[] = [
  {
    id: "theme-hub-1",
    title: "Poluição e CSN",
    slug: "poluicao-e-csn",
    excerpt: "Ar, fumaça e impacto cotidiano em torno da siderurgia.",
    description:
      "Eixo que reúne o que a cidade respira, o que o entorno industrial produz e o que vira custo ambiental para bairros e corpos.",
    lead_question: "Quem paga o custo ambiental da cidade e por que isso foi naturalizado?",
    cover_image_url: "/editorial/covers/arquivo-inicial.svg",
    featured: true,
    public_visibility: true,
    sort_order: 1,
    status: "active",
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "theme-hub-2",
    title: "Trabalho e acidentes",
    slug: "trabalho-e-acidentes",
    excerpt: "Turno, risco e desgaste como rotina pública.",
    description:
      "Frente dedicada a lesão, pressão produtiva, adoecimento e a normalização do risco no cotidiano do trabalho operário.",
    lead_question: "Quando o acidente deixa de ser exceção e vira estrutura?",
    cover_image_url: "/archive/assets/acervo-relatorio.svg",
    featured: true,
    public_visibility: true,
    sort_order: 2,
    status: "monitoring",
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "theme-hub-3",
    title: "Cidade e abandono",
    slug: "cidade-e-abandono",
    excerpt: "Infraestrutura, espera e desgaste urbano como política cotidiana.",
    description:
      "Eixo que trata da falha prolongada do espaço público, da manutenção interrompida e da cidade como território de abandono administrado.",
    lead_question: "O que a cidade deixa cair quando o abandono vira normalidade?",
    cover_image_url: "/archive/assets/acervo-foto-oficina.svg",
    featured: true,
    public_visibility: true,
    sort_order: 3,
    status: "active",
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
  {
    id: "theme-hub-4",
    title: "Memória de Volta Redonda",
    slug: "memoria-de-volta-redonda",
    excerpt: "Arquivo vivo da cidade, do trabalho e das disputas pela narrativa pública.",
    description:
      "Frente que cruza fotografia, relato oral, marcos urbanos e documentos para impedir que a história da cidade vire apagamento.",
    lead_question: "Que memória a cidade ainda consegue sustentar contra o esquecimento oficial?",
    cover_image_url: "/archive/assets/acervo-recorte-jornal.svg",
    featured: false,
    public_visibility: true,
    sort_order: 4,
    status: "monitoring",
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
    created_by: null,
    updated_by: null,
  },
];

export const themeHubLinkMockItems: ThemeHubLink[] = [
  {
    id: "theme-hub-link-1",
    theme_hub_id: "theme-hub-1",
    link_type: "editorial",
    link_key: "ar-poeira-e-pressao",
    link_role: "lead",
    timeline_year: 2024,
    timeline_label: "2024",
    timeline_note: "Abertura editorial do eixo sobre poeira e pressão.",
    featured: true,
    sort_order: 1,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
  },
  {
    id: "theme-hub-link-2",
    theme_hub_id: "theme-hub-1",
    link_type: "dossier",
    link_key: "ar-fumaca-e-rotina-industrial",
    link_role: "followup",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Dossiê em curso que costura prova, memória e atualização.",
    featured: true,
    sort_order: 2,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
  },
  {
    id: "theme-hub-link-3",
    theme_hub_id: "theme-hub-1",
    link_type: "memory",
    link_key: "poeira-e-fumaca",
    link_role: "context",
    timeline_year: 1997,
    timeline_label: "fim dos anos 1990",
    timeline_note: "Memória territorial sobre permanência da fumaça.",
    featured: false,
    sort_order: 3,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
  },
  {
    id: "theme-hub-link-4",
    theme_hub_id: "theme-hub-1",
    link_type: "archive",
    link_key: "archive-mock-2",
    link_role: "evidence",
    timeline_year: 2008,
    timeline_label: "2008",
    timeline_note: "Documento-base sobre poeira industrial e pressão cotidiana.",
    featured: false,
    sort_order: 4,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
  },
  {
    id: "theme-hub-link-5",
    theme_hub_id: "theme-hub-1",
    link_type: "collection",
    link_key: "poluicao-e-industria",
    link_role: "archive",
    timeline_year: 2016,
    timeline_label: "2016",
    timeline_note: "Coleção documental da poluição.",
    featured: false,
    sort_order: 5,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
  },
  {
    id: "theme-hub-link-6",
    theme_hub_id: "theme-hub-1",
    link_type: "series",
    link_key: "poluicao-e-csn",
    link_role: "followup",
    timeline_year: 2025,
    timeline_label: "2025",
    timeline_note: "Série que mantém o eixo em movimento público.",
    featured: false,
    sort_order: 6,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
  },
  {
    id: "theme-hub-link-7",
    theme_hub_id: "theme-hub-2",
    link_type: "editorial",
    link_key: "turno-risco-e-lesao",
    link_role: "lead",
    timeline_year: 2025,
    timeline_label: "2025",
    timeline_note: "Peça central sobre acidente, turno e desgaste corporal.",
    featured: true,
    sort_order: 1,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
  },
  {
    id: "theme-hub-link-8",
    theme_hub_id: "theme-hub-2",
    link_type: "dossier",
    link_key: "trabalho-ferido-corpo-insistente",
    link_role: "followup",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Dossiê em acompanhamento sobre rotina de risco.",
    featured: true,
    sort_order: 2,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
  },
  {
    id: "theme-hub-link-9",
    theme_hub_id: "theme-hub-2",
    link_type: "memory",
    link_key: "acidente-e-turno",
    link_role: "context",
    timeline_year: 2004,
    timeline_label: "2004",
    timeline_note: "Memória sobre a normalização do risco no turno.",
    featured: false,
    sort_order: 3,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
  },
  {
    id: "theme-hub-link-10",
    theme_hub_id: "theme-hub-2",
    link_type: "archive",
    link_key: "archive-mock-3",
    link_role: "evidence",
    timeline_year: 2010,
    timeline_label: "2010",
    timeline_note: "Arquivo que sustenta a leitura sobre lesão e pressão.",
    featured: false,
    sort_order: 4,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
  },
  {
    id: "theme-hub-link-11",
    theme_hub_id: "theme-hub-3",
    link_type: "editorial",
    link_key: "o-que-sobrou-da-promessa-industrial",
    link_role: "lead",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Entrada central do eixo sobre abandono urbano.",
    featured: true,
    sort_order: 1,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
  },
  {
    id: "theme-hub-link-12",
    theme_hub_id: "theme-hub-3",
    link_type: "dossier",
    link_key: "cidade-e-abandono",
    link_role: "followup",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Dossiê concluído que segue como lastro do tema.",
    featured: true,
    sort_order: 2,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
  },
  {
    id: "theme-hub-link-13",
    theme_hub_id: "theme-hub-3",
    link_type: "memory",
    link_key: "apagamentos-e-disputas",
    link_role: "context",
    timeline_year: 1990,
    timeline_label: "anos 1990",
    timeline_note: "Memória sobre apagamentos e disputa do território.",
    featured: false,
    sort_order: 3,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
  },
  {
    id: "theme-hub-link-14",
    theme_hub_id: "theme-hub-3",
    link_type: "archive",
    link_key: "archive-mock-1",
    link_role: "evidence",
    timeline_year: 2012,
    timeline_label: "2012",
    timeline_note: "Fonte documental sobre a cidade deixada em suspenso.",
    featured: false,
    sort_order: 4,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
  },
  {
    id: "theme-hub-link-15",
    theme_hub_id: "theme-hub-4",
    link_type: "memory",
    link_key: "cidade-operaria",
    link_role: "lead",
    timeline_year: 1979,
    timeline_label: "1979",
    timeline_note: "Memória-base da cidade operária em disputa narrativa.",
    featured: true,
    sort_order: 1,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
  },
  {
    id: "theme-hub-link-16",
    theme_hub_id: "theme-hub-4",
    link_type: "dossier",
    link_key: "ar-fumaca-e-rotina-industrial",
    link_role: "followup",
    timeline_year: 2026,
    timeline_label: "2026",
    timeline_note: "Dossiê que atualiza o conflito no presente.",
    featured: false,
    sort_order: 2,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
  },
  {
    id: "theme-hub-link-17",
    theme_hub_id: "theme-hub-4",
    link_type: "collection",
    link_key: "cidade-operaria",
    link_role: "archive",
    timeline_year: 2019,
    timeline_label: "2019",
    timeline_note: "Coleção de base da memória urbana-operária.",
    featured: false,
    sort_order: 3,
    created_at: "2026-03-19T12:00:00.000Z",
    updated_at: "2026-03-19T12:00:00.000Z",
  },
];
